// ============================================================================
//  DrumSynth
//  Teensy 4.0 (ARM Cortex-M7 @ 600MHz)
//  Last modified: 2026-02-14 (Session 9 — v130, BPM display fix)
//
//  3 synthesized drum voices, 32 knobs (2x 16-ch mux), 16 step buttons,
//  10 control buttons, 16 LEDs (shift register), 128x64 OLED (SH1106, software SPI),
//  internal clock with external pulse clock sync on pin 12.
//
//  Transport: STOPPED / RUN_INT / RUN_EXT
//  External clock ISR triggers audio directly (zero-latency) with two-part
//  glitch filter (300µs floor + 25% relative). Lock-in requires 2 consecutive
//  similar intervals. Subdivision scheduling uses measured interval (not EMA).
//  ISR signals main loop via wantSwitchToExt flag.
//  Timeout falls back to RUN_INT (if playing) or STOPPED.
// ============================================================================

#include <Arduino.h>
#include <Mux.h>
#include <ResponsiveAnalogRead.h>
#include <ShiftRegister74HC595.h>
#include <Adafruit_GFX.h>
#include <Fonts/picopixel.h>
#include <Adafruit_SH110X.h>
#include <EEPROM.h>

// Audio objects: names generated by the Teensy Audio Design Tool (https://www.pjrc.com/teensy/gui/).
// Prefix convention: d1/d2/d3 = drum voice, clap/snare = sub-voice, master = output stage.
#include "audiotool.h"
#include "audio_init.h"
#include "bitmaps.h"
#include "hw_setup.h"

#define FIRMWARE_VERSION ".130a"

// Track enum — declared early so Arduino auto-prototypes can reference it
enum Track : uint8_t {
  TRACK_D1 = 0,
  TRACK_D2 = 1,
  TRACK_D3 = 2
};

// overlay and debounce timing
const uint16_t PARAMETER_OVERLAY_DURATION_MS = 500;
const uint16_t DEBOUNCE_DELAY_MS = 10;       // 10ms — fast response for sync
const uint16_t PLAY_DEBOUNCE_MS = 2;       // Play button: minimal debounce for tight sync
const uint16_t BUTTON_DEBOUNCE_MS = 25;    // All other buttons: standard debounce

// D3 accent LED preview state — Main-loop only, no ISR access
bool accentPreviewActive = false;
uint32_t accentPreviewUntilTick = 0;
uint16_t accentPreviewMask = 0;  // 16-bit mask, bit15 = step0 ... bit0 = step15
const uint16_t ACCENT_PREVIEW_DURATION_MS = 2000;

// PPQN selection mode state — main-loop only
bool ppqnModeActive = false;
uint32_t ppqnModeLastActivityTick = 0;  // Last knob/button interaction
uint8_t ppqnModeSelection = 2;          // Currently selected value in mode
static constexpr uint32_t PPQN_MODE_TIMEOUT_MS = 5000;
static constexpr uint32_t PPQN_LONG_PRESS_MS = 5000;

// PPQN options table
const uint8_t PPQN_OPTIONS[] = {1, 2, 4, 24, 48, 96};
constexpr uint8_t PPQN_OPTION_COUNT = 6;

// sequences
byte drum1Sequence[numSteps] = {
  0, 0, 0, 0,
  0, 0, 0, 0,
  0, 0, 0, 0,
  0, 0, 0, 0
};

byte drum2Sequence[numSteps] = {
  0, 0, 0, 0,
  0, 0, 0, 0,
  0, 0, 0, 0,
  0, 0, 0, 0
};

byte drum3Sequence[numSteps] = {
  0, 0, 0, 0,
  0, 0, 0, 0,
  0, 0, 0, 0,
  0, 0, 0, 0
};

// timers
IntervalTimer tickTimer1k;
IntervalTimer stepTimer;

// global time and step
volatile uint32_t sysTickMs = 0;  // Written by sysTickISR, read by main loop

// tempo
// Main-loop only — not accessed from any ISR. rearmStepTimer() is only
// called from setTransport() and setup(), both main-loop context.
float bpm = 120.0f;
volatile int currentStep = 0;  // Written by ISR (triggerStepFromISR), read by main loop

// transport — three states: internal clock, external clock, or stopped
enum TransportState : uint8_t {
  STOPPED   = 0,
  RUN_INT   = 1,   // Internal timer drives steps
  RUN_EXT   = 2    // External pulse ISR drives steps
};

volatile TransportState transportState = STOPPED;  // Read by stepISR, externalClockISR
volatile bool sequencePlaying = false;     // Read by stepISR, externalClockISR

// PPQN for external clock — loaded from EEPROM at boot, selectable via UI.
// ISR reads (externalClockISR), main loop writes (PPQN selection mode).
// uint8_t is atomic on ARM Cortex-M7 — no interrupt guards needed.
volatile uint8_t ppqn = 2;

// ---------------------------------------------------------------------------
// Mid-file includes: These headers define functions/ISRs that reference globals
// declared above. Arduino IDE compiles .ino as a single translation unit, so
// these headers act as inline code segments rather than independent modules.
// ---------------------------------------------------------------------------

// External clock sync — ISRs, state variables, glitch filter, EMA, helpers
// (depends on: TransportState, stepTimer, bpm, ppqn, sequences, triggerD1/D2/D3)
#include "ext_sync.h"

// OLED watchdog and frame timing
// Written: main loop (updateDisplay). Read: sysTickISR (watchdog), main loop (frame limiter).
volatile uint32_t lastFrameDrawTick = 0;
const uint32_t OLED_WATCHDOG_TIMEOUT_MS = 750;
const uint32_t OLED_FRAME_INTERVAL_MS = 67;  // ~15 fps
volatile bool requestOledReinit = false;  // Set by sysTickISR, cleared by main loop

// Oscilloscope — scope buffer, updateScopeData(), drawScopeWaveform()
#include "oscilloscope.h"

// master UI values
int masterLPFBarX = 78;

// drum decays
float d1DecayBase = 75.0f;
float d1Decay = 75.0f;
float d2DecayBase = 75.0f;
float d3DecayBase = 25.0f;

// global choke offset in ms
int chokeOffsetMs = 0;

// D2 noise and clap bases
float clapEffDecayMs = 120.0f;  // Cached: clap decay (from D2 decay) + chokeOffsetMs, floored at 10

// D3 cached effective decay (updated by applyChokeToDecays / accent knob)
float d3CachedDecayMs = 25.0f;

// D1 cached envelope params (updated on knob change / choke change)
float d1CachedAttackMs = 0.5f;
float d1CachedHoldMs = 56.25f;   // d1Decay * 0.75f
float d1CachedDecayMs = 75.0f;   // d1Decay

// parameter overlay text — Main-loop only, no ISR access
char displayParameter1[24] = "";
char displayParameter2[24] = "";
int lastActiveKnob = 255;
uint32_t parameterOverlayStartTick = 0;

// UI voice rails
float uiMixD1Shape = 0.0f;
float uiMixD2Voice = 0.0f;
float uiMixD3Voice = 0.0f;

enum RailMode : uint8_t {
  RAIL_NONE = 0,
  RAIL_D1_SHAPE,
  RAIL_D2_VOICE,
  RAIL_D3_VOICE
};

RailMode activeRail = RAIL_NONE;

// EEPROM persistence — structs, constants, save/load functions
// (must be included after sequences, ppqn, PPQN_OPTIONS, RailMode, UI overlay vars)
#include "eeprom.h"

// delay ratios (in quarter-note units)
static constexpr float quantizeRatios[] = {
  0.125f,       // 1/8  of a quarter = 1/32
  0.25f,        // 1/4  of a quarter = 1/16
  0.33333333f,  // 1/3  of a quarter = 1/8T
  0.5f,         // 1/2  of a quarter = 1/8
  0.66666667f,  // 2/3  of a quarter = 1/4T
  0.75f,        // 3/4  of a quarter = 1/8.
  1.0f,         // 1    quarter      = 1/4
  1.5f,         // 3/2  quarters     = 1/4.
  2.0f,         // 2    quarters     = 1/2
  2.5f,         // 5/2  quarters     = 5/8
  3.0f          // 3    quarters     = 1/2.
};

static constexpr const char* ratioLabels[] = {
  "1/32",
  "1/16",
  "1/8T",
  "1/8",
  "1/4T",
  "1/8.",
  "1/4",
  "1/4.",
  "1/2",
  "5/8",
  "1/2."
};

const int NUM_RATIOS = sizeof(quantizeRatios) / sizeof(quantizeRatios[0]);

// master gain and wavefolder compensation
float masterNominalGain = 1.0f;
float masterWfComp = 1.0f;

// drum levels
float d1Vol = 0.75f;
float d2Vol = 0.75f;
float d3Vol = 0.75f;

// delay sends
float d1DelaySend = 0.0f;
float d2DelaySend = 0.0f;
float d3DelaySend = 0.0f;

// accents
enum AltMode : uint8_t {
  ALT_OFF = 0,
  ALT_HALF,
  ALT_QUARTER,
  ALT_EIGHT,
  ALT_EIGHTUP,
  ALT_VARI1,
  ALT_VARI2,
  ALT_VARI3,
  ALT_VARI4,
  ALT_ALT5,
  ALT_ALT6,
  ALT_ALT7,
  ALT_ALT8,
  ALT_ALT9
};

uint8_t d3AltMode = ALT_OFF;
uint16_t d3AccentMask = 0;  // Cached: accentMaskFromMode(d3AltMode), updated on accent knob change

// Accented hi-hat decay multiplier (2.5x longer decay on accent steps)
const float D3_ACCENT_FACTOR = 2.5f;

// patterns
const uint16_t PAT_VARI1 = 0b1000100000101000;
const uint16_t PAT_VARI2 = 0b1000100010001000;  // NOTE: intentionally same as QUARTER
const uint16_t PAT_VARI3 = 0b1010010010100101;
const uint16_t PAT_VARI4 = 0b0111011101110111;
const uint16_t PAT_ALT5 = 0b0011001100110011;
const uint16_t PAT_ALT6 = 0b0010010010010010;
const uint16_t PAT_ALT7 = 0b1001001001001001;
const uint16_t PAT_ALT8 = 0b0000111100001111;
const uint16_t PAT_ALT9 = 0b1111000011110000;

Track activeTrack = TRACK_D1;  // Main-loop only — no ISR access

// knob smoothing
ResponsiveAnalogRead* analog[knobCount];

// Boot-lock: suppress knob updates until user intentionally moves a knob.
// Prevents ADC drift on power-up from changing parameter values.
static int16_t knobBootValue[knobCount];   // ADC value at boot (after filter settles)
static bool    knobUnlocked[knobCount];    // true once the user has moved this knob
static constexpr int KNOB_UNLOCK_THRESHOLD = 10;  // ADC counts of intentional movement

// helpers
static inline float mapf(int v, int inMin, int inMax, float outMin, float outMax) {
  return outMin + (outMax - outMin) * float(v - inMin) / float(inMax - inMin);
}

static inline float normKnob(int v) {
  if (v < 0) v = 0;
  if (v > 1023) v = 1023;
  return float(v) / 1023.0f;
}

// D1 osc and pitch
float d1BaseFreq = 100.0f;
float d1DistPitchBoost = 0.0f;

static inline void applyD1Freq() {
  float f = d1BaseFreq * (1.0f + d1DistPitchBoost);
  AudioNoInterrupts();
  d1.frequency(f);
  d1b.frequency(f);
  d1c.frequency(f);
  AudioInterrupts();
}

float d1AttackAmt = 0.0f;

// choke mapping helper
static inline int chokeOffsetFromKnob(int v) {
  const int CENTER = 512;
  const int DEADBAND = 50;
  const int MAX_NEG = -40;
  const int MAX_POS = 150;

  // Deadband: center ±50 ADC counts → offset 0ms
  if (v >= CENTER - DEADBAND && v <= CENTER + DEADBAND) {
    return 0;
  }

  // Left of deadband: full CCW → -40ms
  if (v < CENTER - DEADBAND) {
    int lowEnd = CENTER - DEADBAND;
    // t is 0..1 by construction: v is in [0, lowEnd), so numerator ∈ (0, lowEnd]
    float t = float(lowEnd - v) / float(lowEnd);
    return (int)(MAX_NEG * t);
  }

  // Right of deadband: full CW → +150ms
  int highStart = CENTER + DEADBAND;
  // t is 0..1 by construction: v is in (highStart, 1023], so numerator ∈ (0, 1023-highStart]
  float t = float(v - highStart) / float(1023 - highStart);
  return (int)(MAX_POS * t);
}

// D3 decay helper (includes choke and a small accent boost, capped at 200ms)
static inline float d3EffectiveBaseDecay() {
  float base = d3DecayBase + chokeOffsetMs;
  if (base < 7.0f) base = 7.0f;
  if (d3AltMode != ALT_OFF) base += 7.0f;
  if (base > 200.0f) base = 200.0f;
  return base;
}

// D2 decay helper (includes choke, capped at 1000ms)
static inline float d2EffectiveBaseDecay() {
  float base = d2DecayBase + chokeOffsetMs;
  if (base < 15.0f) base = 15.0f;
  if (base > 1000.0f) base = 1000.0f;
  return base;
}

// sequence routing
inline byte* seqByTrack(Track t) {
  switch (t) {
    case TRACK_D1: return drum1Sequence;
    case TRACK_D2: return drum2Sequence;
    case TRACK_D3: return drum3Sequence;
    default:       return drum1Sequence;
  }
}

// forward declarations
void updateOtherButtons();
void updateStepButtons();
void updateLEDs();
void updateDisplay();
void selectSequence(int index);
void playSequence();
void playSequenceCore();
void triggerD1();
void triggerD2();
void triggerD3();
inline int readKnobRaw(byte idx);
inline void updateParameterDisplay(byte idx, int knobValue);
inline void applyKnobToEngine(byte idx, int knobValue);
void updateKnobs();
void setTransport(TransportState s);
inline void updateDrumDelayGains();
void initKnobsFromHardware();
inline void applyMasterGainFromState();
void applyChokeToDecays();
void drawOutlinedText(int x, int y, const char* text);

// Accent pattern bitmask — single source of truth for all 13 accent modes.
// Bit 15 = step 0, bit 0 = step 15.  Used by isAccent() and LED preview.
static inline uint16_t accentMaskFromMode(uint8_t mode) {
  switch (mode) {
    case ALT_HALF: return 0b1000000010000000;     // steps 0 and 8
    case ALT_QUARTER: return 0b1000100010001000;  // steps 0,4,8,12
    case ALT_EIGHT: return 0b1010101010101010;    // even steps (eighth-note pattern)
    case ALT_EIGHTUP: return 0b0101010101010101;  // odd steps (eighth-note upbeat)
    case ALT_VARI1: return PAT_VARI1;
    case ALT_VARI2: return PAT_VARI2;
    case ALT_VARI3: return PAT_VARI3;
    case ALT_VARI4: return PAT_VARI4;
    case ALT_ALT5: return PAT_ALT5;
    case ALT_ALT6: return PAT_ALT6;
    case ALT_ALT7: return PAT_ALT7;
    case ALT_ALT8: return PAT_ALT8;
    case ALT_ALT9: return PAT_ALT9;
    default: return 0;
  }
}

// Accent evaluation — delegates to accentMaskFromMode (single implementation).
// Bit 15 = step 0, bit 0 = step 15; extract the bit for this step.
static inline bool isAccent(uint8_t mode, uint8_t step) {
  return (accentMaskFromMode(mode) >> (15 - (step & 15))) & 1;
}

// Safe even if 32 bit volatile reads can tear on your target.
// On Teensy 3.x and 4.x aligned 32 bit is atomic, but this keeps the logic portable.
static inline uint32_t atomicReadU32(volatile uint32_t& v) {
  uint32_t a, b;
  do {
    a = v;
    b = v;
  } while (a != b);
  return a;
}

// timers and interrupts

void sysTickISR() {
  uint32_t now = sysTickMs + 1;
  sysTickMs = now;

  // stable read of lastFrameDrawTick (handles non atomic 32 bit on some MCUs)
  uint32_t lastDraw = atomicReadU32(lastFrameDrawTick);

  if ((uint32_t)(now - lastDraw) > OLED_WATCHDOG_TIMEOUT_MS) {
    requestOledReinit = true;
  }
}

// audio helpers

inline void updateDrumDelayGains() {
  // Decouple delay sends from the drum output levels.
  // This keeps delay tails and throws consistent even if a drum is turned down or muted.

  float s1 = d1DelaySend;          // 0..1
  float s2 = d2DelaySend;          // 0..1
  float s3 = d3DelaySend * 1.75f;  // D3 needs more send to match D1/D2 levels

  // Keep the combined delay input from getting too hot.
  // (Prevents clipping when multiple sends are high at once.)
  const float SEND_SUM_TARGET = 0.90f;
  float sum = s1 + s2 + s3;
  if (sum > SEND_SUM_TARGET) {
    float k = SEND_SUM_TARGET / sum;
    s1 *= k;
    s2 *= k;
    s3 *= k;
  }

  delayMixer.gain(0, s1);
  delayMixer.gain(1, s2);
  delayMixer.gain(2, s3);
}

inline void applyMasterGainFromState() {
  // always honor masterNominalGain and masterWfComp, even when stopped
  float g = masterNominalGain * masterWfComp;
  masterAmp.gain(g);
}

// Recompute cached D1 envelope params from d1Decay and d1AttackAmt.
// Call whenever either changes (choke offset, decay knob, or attack knob).
static inline void updateD1EnvelopeCache() {
  d1CachedAttackMs = 0.5f + 20.0f * d1AttackAmt;
  d1CachedHoldMs = d1Decay * 0.75f + 12.0f * d1AttackAmt;
  d1CachedDecayMs = d1Decay * (1.0f - 0.25f * d1AttackAmt);
}

// choke application on all relevant decays

void applyChokeToDecays() {
  // D1: floor at 17 ms
  float eff1 = d1DecayBase + chokeOffsetMs;
  if (eff1 < 17.0f) eff1 = 17.0f;
  d1Decay = eff1;

  // Update D1 envelope cache
  updateD1EnvelopeCache();

  AudioNoInterrupts();
  d1AmpEnv.hold(d1CachedHoldMs);
  d1AmpEnv.decay(d1CachedDecayMs);
  AudioInterrupts();

  // D2 main decay using helper
  float base2 = d2EffectiveBaseDecay();
  AudioNoInterrupts();
  d2AmpEnv.hold(base2 * 0.5f);
  d2AmpEnv.decay(base2);
  drum2.length(base2 * 0.25f);
  AudioInterrupts();

  // D2 clap family — derive clap decay from D2 decay (50–1000ms → 120–275ms)
  float d2Norm = (d2DecayBase - 50.0f) / (1000.0f - 50.0f);
  if (d2Norm < 0.0f) d2Norm = 0.0f;
  if (d2Norm > 1.0f) d2Norm = 1.0f;
  float clapDecayBase = 120.0f + d2Norm * (275.0f - 120.0f);
  clapEffDecayMs = clapDecayBase + chokeOffsetMs;
  if (clapEffDecayMs < 10.0f) clapEffDecayMs = 10.0f;

  // Cache D3 effective decay for use in triggerD3()
  d3CachedDecayMs = d3EffectiveBaseDecay();

  AudioNoInterrupts();
  clap1AmpEnv.decay(clapEffDecayMs);
  clap2AmpEnv.decay(clapEffDecayMs);
  clapMasterEnv.decay(clapEffDecayMs);
  AudioInterrupts();
}

void setup() {
  delay(200);

  // ============================================================================
  // STARTUP LED BLINK (3x flash)
  // ============================================================================

  pinMode(LED_BUILTIN, OUTPUT);
  for (int i = 0; i < 3; i++) {
    digitalWrite(LED_BUILTIN, HIGH);
    delay(150);
    digitalWrite(LED_BUILTIN, LOW);
    delay(150);
  }

  // ============================================================================
  // OLED DISPLAY INITIALIZATION
  // ============================================================================

  // Args: (i2cAddr=0 unused for SPI, reset=true to hardware-reset the display)
  bool displayOk = display.begin(0, true);
  if (displayOk) {
    display.clearDisplay();

    // Startup splash screen
    display.setTextColor(1);
    display.setTextWrap(false);
    display.setFont(NULL);
    display.setTextSize(1);
    display.setCursor(40, 20);
    display.print("VERSION");
    display.setTextSize(1);
    display.setCursor(43, 36);
    display.print("v" FIRMWARE_VERSION);
    display.display();
    delay(800);

    display.clearDisplay();
    display.display();
  }

  // ============================================================================
  // AUDIO SYSTEM INITIALIZATION
  // ============================================================================

  AudioMemory(500);
  tickTimer1k.begin(sysTickISR, 1000);
  audioInit();
  scopeQueue.begin();

  // ============================================================================
  // UI STATE INITIALIZATION
  // ============================================================================

  // Clear overlay and parameter strings at boot (now sysTickMs is valid)
  activeRail = RAIL_NONE;
  lastActiveKnob = 255;
  displayParameter1[0] = 0;
  displayParameter2[0] = 0;

  noInterrupts();
  parameterOverlayStartTick = sysTickMs - PARAMETER_OVERLAY_DURATION_MS - 1;
  interrupts();

  // Load saved PPQN from EEPROM (defaults to 2 if nothing saved)
  loadPpqnFromEEPROM();

  // ============================================================================
  // HARDWARE INITIALIZATION
  // ============================================================================

  // Initialize shift register and LEDs
  sr.setAllLow();
  updateLEDs();

  // Initialize knob smoothing filters
  for (byte i = 0; i < knobCount; i++) {
    analog[i] = new ResponsiveAnalogRead(0, true);
    analog[i]->setActivityThreshold(20);
  }

  // ============================================================================
  // EXTERNAL CLOCK PIN
  // ============================================================================

  pinMode(EXT_CLK_PIN, INPUT_PULLDOWN);
  attachInterrupt(digitalPinToInterrupt(EXT_CLK_PIN), externalClockISR, RISING);

  // ============================================================================
  // LOAD STATE AND START SEQUENCER
  // ============================================================================

  initKnobsFromHardware();
  loadStateFromEEPROM(activeSaveSlot);
  rearmStepTimer();
  applyMasterGainFromState();
}

void loop() {

  // ============================================================================
  // ACCENT PREVIEW TIMEOUT
  // ============================================================================

  // Expire accent preview and restore normal LEDs
  if (accentPreviewActive) {
    uint32_t nowTick;
    noInterrupts();
    nowTick = sysTickMs;  // sysTickMs is ISR-written, needs guard
    interrupts();

    if ((int32_t)(nowTick - accentPreviewUntilTick) >= 0) {
      accentPreviewActive = false;  // Main-loop only — no guard needed
      updateLEDs();
    }
  }

  // PPQN mode timeout — auto-exit without saving after 5s inactivity
  if (ppqnModeActive) {
    uint32_t nowTick;
    noInterrupts();
    nowTick = sysTickMs;
    interrupts();
    if ((uint32_t)(nowTick - ppqnModeLastActivityTick) >= PPQN_MODE_TIMEOUT_MS) {
      ppqnModeActive = false;
      // No save — just exit silently. Normal display resumes automatically.
    }
  }

  // ============================================================================
  // OLED WATCHDOG RECOVERY
  // ============================================================================

  // Atomic check-and-clear prevents losing a flag set between the
  // if-check and the clear (ISR could fire in between otherwise)
  {
    bool needsReinit;
    noInterrupts();
    needsReinit = requestOledReinit;
    requestOledReinit = false;
    interrupts();

    if (needsReinit) {
      display.begin(0, true);  // i2cAddr=0 unused for SPI, reset=true
      display.clearDisplay();
      display.display();

      uint32_t t;
      noInterrupts();
      t = sysTickMs;
      lastFrameDrawTick = t;
      interrupts();
    }
  }

  // ============================================================================
  // EXTERNAL CLOCK: lock-in handoff + timeout detection (ext_sync.h)
  // ============================================================================

  checkExtClockLockIn();
  checkExtClockTimeout();

  // ============================================================================
  // SEQUENCER STEP PROCESSING (before input polling to minimize latency)
  // ============================================================================

  if (sequencePlaying) {
    if (transportState == RUN_EXT) {
      // External clock: audio triggers fire directly in ISR (triggerStepFromISR).
      // Main loop handles deferred LED update only.
      if (ledUpdatePending) {
        updateLEDs();
        // Clear AFTER the update so any ISR that fires during updateLEDs()
        // re-sets the flag and is caught on the next loop iteration.
        noInterrupts();
        ledUpdatePending = false;
        interrupts();
      }
    } else {
      // Internal clock: consume steps queued by stepISR
      playSequence();
    }
  }
  // Gain is already applied by knob handlers — no per-loop update needed when stopped

  updateExtBpmDisplay();

  // ============================================================================
  // USER INPUT POLLING
  // ============================================================================

  updateOtherButtons();
  updateKnobs();
  updateStepButtons();

  // ============================================================================
  // OSCILLOSCOPE DATA ACQUISITION
  // ============================================================================

  updateScopeData();

  // ============================================================================
  // THROTTLED OLED REFRESH (15 FPS to reduce lag)
  // ============================================================================

  uint32_t tickCopy, lastDrawCopy;

  noInterrupts();
  tickCopy = sysTickMs;
  lastDrawCopy = lastFrameDrawTick;
  interrupts();

  if ((uint32_t)(tickCopy - lastDrawCopy) >= OLED_FRAME_INTERVAL_MS) {
    updateDisplay();
  }
}

// transport helpers — v126 pattern: clean state transitions
void setTransport(TransportState s) {
  if (transportState == s) return;
  transportState = s;

  // When leaving RUN_EXT, clear step accumulator and cancel subdivisions
  if (transportState != RUN_EXT) {
    extStepAcc = 0;
    stepTimer.end();        // Cancel any in-flight subdivision timer
    subdivRemaining = 0;
  }

  switch (transportState) {
    case RUN_INT:
      rearmStepTimer();
      break;
    case RUN_EXT:
      stepTimer.end();
      // Don't clear extStepAcc here — the ISR may have already written a valid
      // accumulator value on the locking pulse before main loop calls setTransport().
      // Clearing happens when *leaving* RUN_EXT (see above).
      break;
    case STOPPED:
    default:
      stepTimer.end();
      break;
  }
}

// sequencing and triggers

void playSequence() {
  // pendingStepCount is uint8_t (atomic on ARM), but read-and-clear
  // must be done atomically to avoid losing a count
  uint8_t toDo;
  noInterrupts();
  toDo = pendingStepCount;
  pendingStepCount = 0;
  interrupts();

  if (toDo == 0) return;

  if (toDo > 32) toDo = 32;
  while (toDo--) {
    playSequenceCore();
  }
}

// Advance one step and trigger active drums.
// Called from main loop context (internal clock path), so safe to call updateLEDs().
void playSequenceCore() {
  if (currentStep < 0 || currentStep >= numSteps) {
    currentStep = numSteps - 1;
  }
  currentStep = (currentStep + 1) % numSteps;

  if (drum1Sequence[currentStep]) triggerD1();
  if (drum2Sequence[currentStep]) triggerD2();
  if (drum3Sequence[currentStep]) triggerD3();

  // Update LEDs — safe in main-loop context (SPI not safe from ISR)
  updateLEDs();
}

void triggerD1() {
  uint32_t now = micros();
  noInterrupts();
  bool skipNoteOff = (now - lastD1TriggerUs) < MIN_RETRIGGER_US;
  lastD1TriggerUs = now;
  interrupts();

  // Use pre-computed envelope params (updated by applyChokeToDecays / attack knob)
  AudioNoInterrupts();
  d1AmpEnv.attack(d1CachedAttackMs);
  d1AmpEnv.hold(d1CachedHoldMs);
  d1AmpEnv.decay(d1CachedDecayMs);
  AudioInterrupts();

  if (!skipNoteOff) {
    d1AmpEnv.noteOff();
    d1PitchEnv.noteOff();
  }
  d1AmpEnv.noteOn();
  d1PitchEnv.noteOn();
  drum1.noteOn();
}

// Trigger D2 (snare/clap) — shared by ISR and main-loop step functions.
// Handles retrigger guard and envelope noteOff/noteOn.
// Decay values are already set by applyChokeToDecays() when choke or decay knob changes.
void triggerD2() {
  uint32_t now = micros();
  noInterrupts();
  bool skipNoteOff = (now - lastD2TriggerUs) < MIN_RETRIGGER_US;
  lastD2TriggerUs = now;
  interrupts();

  if (!skipNoteOff) {
    d2AmpEnv.noteOff();
    clap1AmpEnv.noteOff();
    clap2AmpEnv.noteOff();
    clapMasterEnv.noteOff();
    d2NoiseEnvelope.noteOff();
  }
  d2AmpEnv.noteOn();
  clap1AmpEnv.noteOn();
  clap2AmpEnv.noteOn();
  clapMasterEnv.noteOn();
  drum2.noteOn();
  d2Attack.noteOn();
  d2NoiseEnvelope.noteOn();
}

// Trigger D3 (hi-hat) — shared by ISR and main-loop step functions.
// Applies accent pattern if active, handles retrigger guard.
void triggerD3() {
  uint32_t now = micros();
  noInterrupts();
  bool skipNoteOff = (now - lastD3TriggerUs) < MIN_RETRIGGER_US;
  lastD3TriggerUs = now;
  interrupts();

  // Use cached decay and accent mask (updated by applyChokeToDecays / accent knob)
  float applyDecay = d3CachedDecayMs;

  if (d3AccentMask && ((d3AccentMask >> (15 - (currentStep & 15))) & 1)) {
    applyDecay *= D3_ACCENT_FACTOR;
  }

  AudioNoInterrupts();
  d3AmpEnv.decay(applyDecay);
  d3606AmpEnv.decay(applyDecay);
  drum3.length(applyDecay);
  AudioInterrupts();

  if (!skipNoteOff) {
    d3AmpEnv.noteOff();
    d3606AmpEnv.noteOff();
  }
  d3AmpEnv.noteOn();
  d3606AmpEnv.noteOn();
  drum3.noteOn();
}

// buttons and LEDs

void updateOtherButtons() {
  static uint32_t lastDebounceTick[otherButtonsCount] = { 0 };
  static bool state[otherButtonsCount] = { false };
  static bool lastState[otherButtonsCount] = { false };

  // Button 7 long-hold state — shared between state-change and continuous-hold blocks
  static uint32_t btn7PressTick = 0;
  static bool btn7EnteredPpqn = false;

  uint32_t nowTick;
  noInterrupts();
  nowTick = sysTickMs;
  interrupts();

  for (int i = 0; i < otherButtonsCount; i++) {

    otherButtonsMux.channel(i);
    delayMicroseconds(5);

    bool rawPressed = !otherButtonsMux.read();  // no arg — use channel already set above

    if (rawPressed != lastState[i]) {
      lastDebounceTick[i] = nowTick;
    }

    uint16_t debounceTicks = (i == 6) ? PLAY_DEBOUNCE_MS : BUTTON_DEBOUNCE_MS;
    if ((uint32_t)(nowTick - lastDebounceTick[i]) > debounceTicks && (rawPressed != state[i])) {

      state[i] = rawPressed;

      // Button 7 (CHANGE MEMORY SLOT) — state transitions only.
      // 5s hold detection is in continuous check below.
      if (i == 7) {
        if (state[7]) {
          // Press down — record timestamp
          btn7PressTick = nowTick;
          btn7EnteredPpqn = false;
        } else {
          // Release
          if (btn7EnteredPpqn) {
            // Hold already entered PPQN mode — ignore release (don't cycle slot)
          } else if (ppqnModeActive) {
            // In PPQN mode — confirm and save
            ppqn = ppqnModeSelection;
            savePpqnToEEPROM(ppqn);
            if (transportState == RUN_EXT) {
              noInterrupts();
              extStepAcc = 0;
              interrupts();
            }
            ppqnModeActive = false;
            snprintf(displayParameter1, sizeof(displayParameter1), "PPQN %d", ppqn);
            snprintf(displayParameter2, sizeof(displayParameter2), "SAVED");
            parameterOverlayStartTick = nowTick;
            activeRail = RAIL_NONE;
            lastActiveKnob = 255;
          } else {
            // Short press — normal cycle memory slot
            activeSaveSlot = (activeSaveSlot + 1) % SAVE_SLOT_COUNT;
          }
          btn7EnteredPpqn = false;
        }
      }

      // Button 7 (MEM) handled separately — see continuous-hold block above
      if (state[i] && i != 7) {
        switch (i) {

          case 0: selectSequence(0); break;
          case 1: selectSequence(1); break;
          case 2: selectSequence(2); break;

          case 3: break;  // Buttons 3-5: hardware-present but unassigned
          case 4: break;
          case 5: break;

          case 6:
            if (!sequencePlaying) {
              // START — reset step position so first emitted step becomes 0
              noInterrupts();
              currentStep = numSteps - 1;
              pendingStepCount = 0;
              extStepAcc = 0;
              interrupts();

              sequencePlaying = true;
              setTransport(RUN_INT);
            } else {
              // STOP — setTransport(STOPPED) clears extStepAcc internally
              sequencePlaying = false;
              setTransport(STOPPED);
              applyMasterGainFromState();
            }
            break;

          case 8:
            sequencePlaying = false;
            setTransport(STOPPED);
            applyMasterGainFromState();

            loadStateFromEEPROM(activeSaveSlot);
            updateLEDs();

            // Ensure next START begins at step 0 again
            noInterrupts();
            currentStep = numSteps - 1;
            pendingStepCount = 0;
            interrupts();

            break;

          case 9:
            {
              activeRail = RAIL_NONE;
              lastActiveKnob = 255;

              if (sequencePlaying) {
                snprintf(displayParameter1, sizeof(displayParameter1), "STOP");
                snprintf(displayParameter2, sizeof(displayParameter2), "TO SAVE");
              } else {
                if (patternDirty) saveStateToEEPROM(activeSaveSlot);
                snprintf(displayParameter1, sizeof(displayParameter1), "PATTERN");
                snprintf(displayParameter2, sizeof(displayParameter2), "SAVED");
              }

              parameterOverlayStartTick = nowTick;
              break;
            }

          default:
            break;
        }
      }
    }

    // Button 7 continuous hold check — enters PPQN mode after 5s while held.
    // Runs on every scan iteration (not just state change). Uses function-scope
    // btn7PressTick/btn7EnteredPpqn shared with the state-change block above.
    if (i == 7 && state[7] && !ppqnModeActive && !btn7EnteredPpqn) {
      if ((uint32_t)(nowTick - btn7PressTick) >= PPQN_LONG_PRESS_MS) {
        ppqnModeActive = true;
        ppqnModeLastActivityTick = nowTick;
        ppqnModeSelection = ppqn;
        btn7EnteredPpqn = true;  // Prevent release from cycling slot
      }
    }

    lastState[i] = rawPressed;
  }
}

void selectSequence(int index) {
  switch (index) {
    case 0: activeTrack = TRACK_D1; break;
    case 1: activeTrack = TRACK_D2; break;
    case 2: activeTrack = TRACK_D3; break;
    default: return;
  }
  updateLEDs();
}

void updateLEDs() {
  // Main-loop only — no ISR access to accentPreview*, no guards needed
  bool preview = accentPreviewActive;
  uint16_t mask = accentPreviewMask;

  // Accent preview mode (temporary display)
  if (preview) {
    for (int i = 0; i < numSteps; i++) {
      bool on = (mask >> (15 - i)) & 1;
      sr.set(i, on);
    }
    return;
  }

  // Normal pattern display with optional current step indicator
  byte* seq = seqByTrack(activeTrack);

  // Snapshot current step and play state atomically
  int currentStepSnap;
  bool playingSnap;
  noInterrupts();
  currentStepSnap = currentStep;
  playingSnap = sequencePlaying;
  interrupts();

  for (int i = 0; i < numSteps; i++) {
    bool ledState = seq[i];

    // Force current step ON when playing (creates moving bright spot)
    if (playingSnap && i == currentStepSnap) {
      ledState = true;
    }

    sr.set(i, ledState);
  }
}

void updateStepButtons() {
  static uint32_t lastDebounceTick[stepButtonCount] = { 0 };
  static bool state[stepButtonCount] = { false };
  static bool lastState[stepButtonCount] = { false };

  byte* seq = seqByTrack(activeTrack);

  // single stable timebase for this whole scan
  uint32_t nowTick;
  noInterrupts();
  nowTick = sysTickMs;
  interrupts();

  for (int i = 0; i < stepButtonCount; i++) {
    stepButtonsMux.channel(i);
    delayMicroseconds(5);
    bool rawPressed = !stepButtonsMux.read();  // no arg — use channel already set above

    if (rawPressed != lastState[i]) {
      lastDebounceTick[i] = nowTick;
    }

    if ((uint32_t)(nowTick - lastDebounceTick[i]) > DEBOUNCE_DELAY_MS && (rawPressed != state[i])) {

      state[i] = rawPressed;
      if (state[i]) {
        seq[i] ^= 1;
        sr.set(i, seq[i]);
        patternDirty = true;
      }
    }

    lastState[i] = rawPressed;
  }
}

int readKnobRaw(byte idx) {
  int raw;
  if (idx < 16) {
    knobMux1.channel(idx);
    delayMicroseconds(5);
    raw = knobMux1.read();  // no arg — use channel already set above
  } else {
    knobMux2.channel(idx - 16);
    delayMicroseconds(5);
    raw = knobMux2.read();  // no arg — use channel already set above
  }
  // Clamp ADC edges: pots rarely hit true 0/1023 — map the reliable
  // range to the full 0-1023 so both extremes are always reachable.
  raw = constrain(raw, 3, 1020);
  return map(raw, 3, 1020, 0, 1023);
}

void setOverlayTimer(byte idx) {
  lastActiveKnob = idx;
  uint32_t t;
  noInterrupts();
  t = sysTickMs;
  interrupts();
  parameterOverlayStartTick = t;
}

// ============================================================================
//  Shared curve helpers — used by both display and engine switch blocks
//  to keep the mapping in one place.
// ============================================================================

// D1 Decay curve: piecewise 50–70 ms (low range) then 70–1000 ms (high range)
static inline float d1DecayCurve(int knobValue) {
  float norm = normKnob(knobValue);
  if (norm <= 0.25f) {
    float blend = norm / 0.25f;
    return 50.0f + (70.0f - 50.0f) * blend;
  } else {
    float blend = (norm - 0.25f) / 0.75f;
    return 70.0f + (1000.0f - 70.0f) * blend;
  }
}

// D1 Pitch curve: piecewise 60–105 Hz (low) then 105–500 Hz (high)
static inline float d1PitchCurve(int knobValue) {
  float norm = normKnob(knobValue);
  if (norm <= 0.33f) {
    float blend = norm / 0.33f;
    return 60.0f + (105.0f - 60.0f) * blend;
  } else {
    float blend = (norm - 0.33f) / 0.67f;
    return 105.0f + (500.0f - 105.0f) * blend;
  }
}

// D2 Decay curve: piecewise 50–300 ms (low half) then 300–1000 ms (high half)
static inline float d2DecayCurve(int knobValue) {
  float norm = knobValue / 1023.0f;
  if (norm <= 0.5f) {
    return 50.0f + (300.0f - 50.0f) * (norm / 0.5f);
  } else {
    return 300.0f + (1000.0f - 300.0f) * ((norm - 0.5f) / 0.5f);
  }
}

// BPM curve: 60–300 (first 80%) then 900–1000 (remaining 20%, hyperspeed), rounded to 0.5
// NOTE: The 300–900 gap is intentional — hyperspeed is a separate creative effect.
static inline float bpmFromKnob(int knobValue) {
  float norm = normKnob(knobValue);
  float bpmValue;
  if (norm <= 0.80f) {
    // 0–80%: 60 → 300 BPM (normal range)
    float blend = norm / 0.80f;
    bpmValue = 60.0f + blend * (300.0f - 60.0f);
  } else {
    // 80–100%: 900 → 1000 BPM (hyperspeed)
    float blend = (norm - 0.80f) / 0.20f;
    bpmValue = 900.0f + blend * (1000.0f - 900.0f);
  }
  return floorf(bpmValue * 2.0f + 0.5f) * 0.5f;
}

// Accent mode from knob position — maps knob to one of 13 accent patterns
static inline uint8_t accentModeFromKnob(int knobValue) {
  const int ACCENT_DEADBAND = 24;
  if (knobValue <= ACCENT_DEADBAND) {
    return ALT_OFF;
  }
  int zone = map(knobValue, ACCENT_DEADBAND + 1, 1023, 1, 13);
  switch (zone) {
    case 1: return ALT_HALF;
    case 2: return ALT_QUARTER;
    case 3: return ALT_EIGHT;
    case 4: return ALT_EIGHTUP;
    case 5: return ALT_VARI1;
    case 6: return ALT_VARI2;
    case 7: return ALT_VARI3;
    case 8: return ALT_VARI4;
    case 9: return ALT_ALT5;
    case 10: return ALT_ALT6;
    case 11: return ALT_ALT7;
    case 12: return ALT_ALT8;
    case 13: return ALT_ALT9;
    default: return ALT_ALT9;
  }
}

// Delay ratio index from knob — finds the closest beat-synced ratio within delay limit
static inline int delayRatioFromKnob(int knobValue, float currentBpm) {
  float msPerBeat = 60000.0f / currentBpm;
  float maxRatio = 1400.0f / msPerBeat;

  int maxIdx = 0;
  for (int i = 0; i < NUM_RATIOS; i++) {
    if (quantizeRatios[i] <= maxRatio) {
      maxIdx = i;
    } else {
      break;
    }
  }

  int ratioIdx = (int)((knobValue / 1023.0f) * maxIdx + 0.5f);
  return constrain(ratioIdx, 0, maxIdx);
}

// parameter overlay text

void updateParameterDisplay(byte idx, int knobValue) {
  setOverlayTimer(idx);
  activeRail = RAIL_NONE;

  switch (idx) {

      // ========================================================================
      // D1 - KICK DRUM (Knobs 0-7)
      // ========================================================================

    case 0:  // D1 Drive/Distortion
      {
        int percent = (int)map(knobValue, 0, 1023, 1, 100);
        snprintf(displayParameter1, sizeof(displayParameter1), "D1 DISTORT");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d%%", percent);
        break;
      }

    case 1:  // D1 Waveform Shape (uses rail display)
      {
        displayParameter1[0] = 0;
        displayParameter2[0] = 0;
        activeRail = RAIL_D1_SHAPE;
        uiMixD1Shape = normKnob(knobValue);
        break;
      }

    case 2:  // D1 Decay
      {
        float decayMs = d1DecayCurve(knobValue);
        snprintf(displayParameter1, sizeof(displayParameter1), "D1 DECAY");
        snprintf(displayParameter2, sizeof(displayParameter2), "%.0f ms", decayMs);
        break;
      }

    case 3:  // D1 Pitch
      {
        float freqHz = d1PitchCurve(knobValue);
        snprintf(displayParameter1, sizeof(displayParameter1), "D1 FREQUENCY");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d Hz", (int)freqHz);
        break;
      }

    case 4:  // D1 Volume
      {
        float norm = normKnob(knobValue);
        int percent = (int)(norm * 100.0f + 0.5f);
        snprintf(displayParameter1, sizeof(displayParameter1), "D1 VOLUME");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d%%", percent);
        break;
      }

    case 5:  // D1 Attack/Snap
      {
        int percent = (int)map(knobValue, 0, 1023, 0, 100);
        snprintf(displayParameter1, sizeof(displayParameter1), "D1 SNAP");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d%%", percent);
        break;
      }

    case 6:  // D1 EQ (Body)
      {
        int percent = (int)map(knobValue, 0, 1023, 0, 100);
        snprintf(displayParameter1, sizeof(displayParameter1), "D1 BODY");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d%%", percent);
        break;
      }

    case 7:  // D1 Delay Send
      {
        // Capped at 75% to prevent feedback runaway
        int percent = (int)map(knobValue, 0, 1023, 0, 75);
        snprintf(displayParameter1, sizeof(displayParameter1), "D1 DLY SEND");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d%%", percent);
        break;
      }

      // ========================================================================
      // D2 - SNARE/CLAP (Knobs 8-15)
      // ========================================================================

    case 8:  // D2 Pitch
      {
        float freqHz = mapf(knobValue, 0, 1023, 100.0f, 300.0f);
        snprintf(displayParameter1, sizeof(displayParameter1), "D2 SNARE FREQ");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d Hz", (int)freqHz);
        break;
      }

    case 9:  // D2 Decay
      {
        float decayMs = d2DecayCurve(knobValue);
        snprintf(displayParameter1, sizeof(displayParameter1), "D2 DECAY");
        snprintf(displayParameter2, sizeof(displayParameter2), "%.0f ms", decayMs);
        break;
      }

    case 10:  // D2 Voice Mix - Snare/Clap (uses rail display)
      {
        displayParameter1[0] = 0;
        displayParameter2[0] = 0;
        activeRail = RAIL_D2_VOICE;
        uiMixD2Voice = normKnob(knobValue);
        break;
      }

    case 11:  // D2 Wavefolder Drive
      {
        float norm = normKnob(knobValue);
        int percent = (int)(norm * 100.0f + 0.5f);
        snprintf(displayParameter1, sizeof(displayParameter1), "D2 DISTORT");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d%%", percent);
        break;
      }

    case 12:  // D2 Delay Send
      {
        // Capped at 75% to prevent feedback runaway
        int percent = (int)map(knobValue, 0, 1023, 0, 75);
        snprintf(displayParameter1, sizeof(displayParameter1), "D2 DLY SEND");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d%%", percent);
        break;
      }

    case 13:  // D2 Reverb
      {
        float norm = normKnob(knobValue);
        int percent = (int)(norm * 100.0f + 0.5f);

        snprintf(displayParameter1, sizeof(displayParameter1), "D2 REVERB");

        if (percent < 5) {
          snprintf(displayParameter2, sizeof(displayParameter2), "OFF");
        } else {
          snprintf(displayParameter2, sizeof(displayParameter2), "%d%%", percent);
        }
        break;
      }

    case 14:  // D2 Noise
      {
        snprintf(displayParameter1, sizeof(displayParameter1), "D2 NOISE");
        if (knobValue < 5) {
          snprintf(displayParameter2, sizeof(displayParameter2), "OFF");
        } else {
          int percent = (int)map(knobValue, 5, 1023, 1, 100);
          snprintf(displayParameter2, sizeof(displayParameter2), "%d%%", percent);
        }
        break;
      }

    case 15:  // D2 Volume
      {
        float norm = normKnob(knobValue);
        float volume = norm * 3.5f;
        if (volume > 2.3f) volume = 2.3f;
        int percent = (int)(volume / 2.3f * 100.0f + 0.5f);
        snprintf(displayParameter1, sizeof(displayParameter1), "D2 VOLUME");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d%%", percent);
        break;
      }

      // ========================================================================
      // D3 - HI-HAT (Knobs 16-23)
      // ========================================================================

    case 16:  // D3 Pitch (displayed as generic "tune")
      {
        int tune = (int)(normKnob(knobValue) * 100.0f + 0.5f);
        snprintf(displayParameter1, sizeof(displayParameter1), "D3 TUNE");
        snprintf(displayParameter2, sizeof(displayParameter2), "%3d", tune);
        break;
      }

    case 17:  // D3 Decay
      {
        float decayMs = map(knobValue, 0, 1023, 100, 1200) * 0.1f;
        snprintf(displayParameter1, sizeof(displayParameter1), "D3 DECAY");
        snprintf(displayParameter2, sizeof(displayParameter2), "%.0f ms", decayMs);
        break;
      }

    case 18:  // D3 Voice Mix - 3-way (uses rail display)
      {
        displayParameter1[0] = 0;
        displayParameter2[0] = 0;
        activeRail = RAIL_D3_VOICE;
        uiMixD3Voice = normKnob(knobValue);
        break;
      }

    case 19:  // D3 Wavefolder Drive
      {
        int percent = (int)map(knobValue, 0, 1023, 1, 100);
        snprintf(displayParameter1, sizeof(displayParameter1), "D3 DISTORT");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d%%", percent);
        break;
      }

    case 20:  // D3 Delay Send
      {
        // Capped at 75% to prevent feedback runaway (same as D1/D2)
        int percent = (int)map(knobValue, 0, 1023, 0, 75);
        snprintf(displayParameter1, sizeof(displayParameter1), "D3 DLY SEND");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d%%", percent);
        break;
      }

    case 21:  // D3 Filter
      {
        float norm = normKnob(knobValue);
        float normSq = norm * norm;
        float cutoffHz = 4500.0f + normSq * (8000.0f - 4500.0f);

        snprintf(displayParameter1, sizeof(displayParameter1), "D3 LOWPASS");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d Hz", (int)cutoffHz);
        break;
      }

    case 22:  // D3 Accent Pattern
      {
        snprintf(displayParameter1, sizeof(displayParameter1), "D3 ACCENT");
        displayParameter2[0] = 0;
        break;
      }

    case 23:  // D3 Volume
      {
        float norm = normKnob(knobValue);
        float volume = norm * 5.0f;
        if (volume > 3.5f) volume = 3.5f;
        int percent = (int)(volume / 3.5f * 100.0f + 0.5f);
        snprintf(displayParameter1, sizeof(displayParameter1), "D3 VOLUME");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d%%", percent);
        break;
      }

      // ========================================================================
      // MASTER SECTION (Knobs 24-31)
      // ========================================================================

    case 24:  // Master Delay Time (quantized to tempo)
      {
        int ratioIdx = delayRatioFromKnob(knobValue, bpm);
        snprintf(displayParameter1, sizeof(displayParameter1), "DELAY TIME");
        snprintf(displayParameter2, sizeof(displayParameter2), "%s", ratioLabels[ratioIdx]);
        break;
      }

    case 25:  // Wavefold Frequency
      {
        int percent = (int)(normKnob(knobValue) * 100.0f + 0.5f);
        snprintf(displayParameter1, sizeof(displayParameter1), "WAVEFOLD FRQ");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d%%", percent);
        break;
      }

    case 26:  // Master Lowpass Filter
      {
        int freqHz = (int)map(knobValue, 0, 1023, 1000, 7500);
        snprintf(displayParameter1, sizeof(displayParameter1), "MASTER LPF");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d Hz", freqHz);
        break;
      }

    case 27:  // Master Tempo (BPM) — inactive during external clock, PPQN selector in mode
      {
        if (ppqnModeActive) {
          // Map knob to discrete PPQN bins
          int bin = map(knobValue, 0, 1023, 0, PPQN_OPTION_COUNT - 1);
          bin = constrain(bin, 0, PPQN_OPTION_COUNT - 1);
          ppqnModeSelection = PPQN_OPTIONS[bin];
          uint32_t t;
          noInterrupts();
          t = sysTickMs;
          interrupts();
          ppqnModeLastActivityTick = t;
          snprintf(displayParameter1, sizeof(displayParameter1), "PPQN");
          snprintf(displayParameter2, sizeof(displayParameter2), "%d", ppqnModeSelection);
          break;
        }

        if (transportState == RUN_EXT) {
          snprintf(displayParameter1, sizeof(displayParameter1), "EXT MODE");
          displayParameter2[0] = 0;
          break;
        }

        float bpmValue = bpmFromKnob(knobValue);

        snprintf(displayParameter1, sizeof(displayParameter1), "BPM");
        snprintf(displayParameter2, sizeof(displayParameter2), "%.1f", bpmValue);
        break;
      }

    case 28:  // Master Volume
      {
        float norm = normKnob(knobValue);
        int percent = (int)(norm * 100.0f + 0.5f);
        snprintf(displayParameter1, sizeof(displayParameter1), "MASTER VOL");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d%%", percent);
        break;
      }

    case 29:  // Master Choke Offset
      {
        float norm = normKnob(knobValue);
        int percent = (int)((norm - 0.5f) * 200.0f);  // -100 to +100

        snprintf(displayParameter1, sizeof(displayParameter1), "DECAY OFFST");
        snprintf(displayParameter2, sizeof(displayParameter2), "%+d%%", percent);
        break;
      }

    case 30:  // Wavefold (master wavefolder drive)
      {
        float norm = normKnob(knobValue);
        const float DEADBAND = 0.05f;
        float active = (norm <= DEADBAND) ? 0.0f
                     : (norm - DEADBAND) / (1.0f - DEADBAND);
        if (active > 1.0f) active = 1.0f;

        // Perceived intensity follows drive² curve
        int percent = (int)(active * active * 100.0f + 0.5f);
        snprintf(displayParameter1, sizeof(displayParameter1), "WAVEFOLD INT");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d%%", percent);
        break;
      }

    case 31:  // Master Delay Mix/Feedback
      {
        int percent = (int)map(knobValue, 0, 1023, 0, 100);
        snprintf(displayParameter1, sizeof(displayParameter1), "DELAY AMT");
        snprintf(displayParameter2, sizeof(displayParameter2), "%d%%", percent);
        break;
      }

      // ========================================================================
      // DEFAULT
      // ========================================================================

    default:
      {
        displayParameter1[0] = 0;
        displayParameter2[0] = 0;
        break;
      }
  }
}

inline void applyKnobToEngine(byte idx, int knobValue) {
  switch (idx) {

      // ========================================================================
      // D1 - KICK DRUM (Knobs 0-7)
      // ========================================================================

    case 0:  // D1 Drive/Distortion
      {
        float norm = normKnob(knobValue);
        float wavefolderAmp = 0.1f + norm * 1.023f;

        d1DCwf.amplitude(wavefolderAmp);
        d1DistPitchBoost = 0.03f * norm;
        applyD1Freq();
        break;
      }

    case 1:  // D1 Waveform Shape
      {
        float norm = normKnob(knobValue);

        // Always keep a sine fundamental present
        const float SIN_FLOOR = 0.35f;
        const float SIN_CEIL = 0.85f;
        const float G_SAW_MAX = 0.55f;
        const float G_SQR_MAX = 0.55f;

        // Calculate voice gains
        float gainSine = SIN_CEIL - (SIN_CEIL - SIN_FLOOR) * norm;
        float gainSaw = 0.0f;
        float gainSquare = 0.0f;

        // Harmonic crossfade: sine → saw → square
        if (norm <= 0.50f) {
          float blend = norm / 0.50f;
          gainSaw = G_SAW_MAX * blend;
        } else {
          float blend = (norm - 0.50f) / 0.50f;
          gainSaw = G_SAW_MAX * (1.0f - blend);
          gainSquare = G_SQR_MAX * blend;
        }

        // Headroom management
        float sum = gainSine + gainSaw + gainSquare;
        float scale = 1.0f;
        const float SUM_TARGET = 0.95f;
        if (sum > SUM_TARGET) {
          scale = SUM_TARGET / sum;
        }

        AudioNoInterrupts();
        d1OscMixer.gain(0, gainSine * scale);
        d1OscMixer.gain(1, gainSaw * scale);
        d1OscMixer.gain(2, gainSquare * scale);
        AudioInterrupts();
        break;
      }

    case 2:  // D1 Decay
      {
        d1DecayBase = d1DecayCurve(knobValue);
        applyChokeToDecays();
        break;
      }

    case 3:  // D1 Pitch
      {
        d1BaseFreq = d1PitchCurve(knobValue);
        applyD1Freq();
        break;
      }

    case 4:  // D1 Volume
      {
        float norm = normKnob(knobValue);
        d1Vol = norm * 0.90f;  // Scaled down ~10% to balance with D2/D3
        drumMixer.gain(0, d1Vol);
        updateDrumDelayGains();
        break;
      }

    case 5:  // D1 Attack/Snap
      {
        float norm = normKnob(knobValue);

        // Pitch snap depth increases with knob
        float pitchDepth = 0.60f + (0.40f * norm);
        drum1.pitchMod(pitchDepth);

        // Transient emphasis, capped at unity
        float transientGain = 0.85f + (0.15f * norm);
        d1Mixer.gain(1, transientGain);

        // Store and update cached envelope params
        d1AttackAmt = norm;
        updateD1EnvelopeCache();
        break;
      }

    case 6:  // D1 EQ (Body)
      {
        float norm = normKnob(knobValue);
        float eqAmount = 0.4f + 0.6f * norm;

        float blend;
        if (eqAmount <= 0.5f) {
          blend = eqAmount / 0.5f;
        } else {
          blend = 1.0f + (eqAmount - 0.5f) / 0.5f;
        }

        float notchFreq0 = 200.0f + 200.0f * blend;
        float notchFreq1 = notchFreq0 * (1.15f + 0.05f * norm);
        float shelfGain = 1.25f * blend;

        AudioNoInterrupts();
        d1EQ.setNotch(0, notchFreq0, 3);
        d1EQ.setNotch(1, notchFreq1, 1);
        d1EQ.setHighShelf(2, 3500.0f, shelfGain, 0.9f);
        AudioInterrupts();
        break;
      }

    case 7:  // D1 Delay Send
      {
        // Capped at 75% to prevent feedback runaway
        float delaySend = map(knobValue, 0, 1023, 0, 75) * 0.01f;
        d1DelaySend = delaySend;
        updateDrumDelayGains();
        break;
      }

      // ========================================================================
      // D2 - SNARE/CLAP (Knobs 8-15)
      // ========================================================================

    case 8:  // D2 Pitch
      {
        float freqHz = mapf(knobValue, 0, 1023, 100.0f, 300.0f);
        d2.frequency(freqHz);
        break;
      }

    case 9:  // D2 Decay
      {
        d2DecayBase = d2DecayCurve(knobValue);
        applyChokeToDecays();
        break;
      }

    case 10:  // D2 Voice Mix - Snare/Clap
      {
        float norm = normKnob(knobValue);

        float gainSnare = norm;
        float gainClap = 1.0f - norm;

        snareClapMixer.gain(0, gainSnare * 1.05f);
        snareClapMixer.gain(1, gainClap * 0.75f);
        break;
      }

    case 11:  // D2 Wavefolder Drive
      {
        float norm = normKnob(knobValue);
        bool offZone = (knobValue < 10);

        // Default values (off state)
        float driveGain = 0.8f;
        float freqHz = 10.0f;
        float lpfFreqHz = 3500.0f;
        float gainDry = 1.0f;
        float gainWet = 0.0f;

        if (!offZone) {
          driveGain = 0.75f + 0.15f * norm;
          freqHz = 20.0f + norm * 800.0f;

          // Wet mix comes in gradually with quadratic curve
          const float WET_START = 0.10f;
          float wetNorm = 0.0f;
          if (norm > WET_START) {
            float blend = (norm - WET_START) / (1.0f - WET_START);
            wetNorm = blend * blend;
          }

          // LPF tracks inversely with drive
          if (norm <= 0.4f) {
            lpfFreqHz = 2500.0f;
          } else {
            float blend = (norm - 0.4f) / 0.6f;
            float blendSquared = blend * blend;
            lpfFreqHz = 2500.0f - blendSquared * (2500.0f - 1500.0f);
          }

          // Dry stays near unity, only pulls down once wet is significant
          gainDry = 1.0f - 0.08f * wetNorm;
          // Wet ramps up with drive (0.0 → 0.5)
          gainWet = wetNorm * 0.5f;
          // Loudness comp: none below 55%, ramps down above (1.0 → 0.72)
          float comp = 1.0f;
          if (norm > 0.55f) {
            float extra = (norm - 0.55f) / 0.45f; // 0→1 over 55%–100%
            comp = 1.0f - 0.28f * extra;
          }
          gainDry *= comp;
          gainWet *= comp;
        }

        // Apply as one atomic update
        AudioNoInterrupts();
        d2WfAmp.gain(driveGain);
        d2WfSine.frequency(freqHz);
        d2WfLowpass.frequency(lpfFreqHz);
        d2MasterMixer.gain(0, gainDry);  // dry
        d2MasterMixer.gain(2, gainWet);  // wavefolder return
        AudioInterrupts();
        break;
      }

    case 12:  // D2 Delay Send
      {
        // Capped at 75% to prevent feedback runaway
        float delaySend = map(knobValue, 0, 1023, 0, 75) * 0.01f;
        d2DelaySend = delaySend;
        updateDrumDelayGains();
        break;
      }

    case 13:  // D2 Reverb
      {
        float norm = normKnob(knobValue);

        if (norm < 0.05f) {
          // Off
          AudioNoInterrupts();
          d2MasterMixer.gain(1, 0.0f);
          AudioInterrupts();
        } else {
          // Active reverb
          float blend = (norm - 0.05f) / 0.95f;
          float roomSize = 0.3f + blend * 0.6f;

          AudioNoInterrupts();
          d2Verb.roomsize(roomSize);
          d2Verb.damping(1.0f);  // Damping always maxed — absorbs high frequencies
          d2MasterMixer.gain(1, blend);
          AudioInterrupts();
        }
        break;
      }

    case 14:  // D2 Noise
      {
        if (knobValue >= 5) {
          float decayMs = (knobValue < 512)
                            ? mapf(knobValue, 5, 511, 30.0f, 70.0f)
                            : mapf(knobValue, 512, 1023, 70.0f, 200.0f);

          d2NoiseEnvelope.hold(decayMs * 0.5f);
          d2NoiseEnvelope.decay(decayMs);

          float filterFreqHz = 3000.0f + 10.0f * decayMs;
          d2NoiseFilter.frequency(filterFreqHz);

          float norm = normKnob(knobValue);
          float noiseGain = 0.045f + 0.27f * norm;
          d2Mixer.gain(2, noiseGain);

          applyChokeToDecays();
        } else {
          // Off
          d2Mixer.gain(2, 0.0f);
        }
        break;
      }

    case 15:  // D2 Volume
      {
        float norm = normKnob(knobValue);
        float volume = norm * 3.5f;
        if (volume > 2.3f) volume = 2.3f;

        d2Vol = volume;
        drumMixer.gain(1, d2Vol);
        updateDrumDelayGains();
        break;
      }

      // ========================================================================
      // D3 - HI-HAT (Knobs 16-23)
      // ========================================================================

    case 16:  // D3 Pitch
      {
        float norm = normKnob(knobValue);

        // --- Shared pitch bend curve (both voices use the same shape) ---
        const float BEND_START = 0.25f;
        float pitchBend;

        if (norm <= BEND_START) {
          float blend = norm / BEND_START;
          pitchBend = 0.60f * blend;
        } else {
          float blend = (norm - BEND_START) / (1.0f - BEND_START);
          pitchBend = 0.60f + 0.40f * (blend * blend);
        }

        // --- Voice 1 (606-ish hats) tuning ---
        // Precomputed logs of constant ratios — expf(x*log) is ~2x faster than powf on Cortex-M7
        static const float LOG_HAT_RATIO  = logf(6000.0f / 400.0f);   // hatMax/hatMin
        static const float LOG_C1_RATIO   = logf(2400.0f / 400.0f);   // c1Max/c1Min
        static const float LOG_C2_RATIO   = logf(4200.0f / 600.0f);   // c2Max/c2Min
        static const float LOG_R1_RATIO   = logf(4.0f / 2.0f);        // r1Max/r1Min
        static const float LOG_R2_RATIO   = logf(6.0f / 4.0f);        // r2Max/r2Min

        const float hatCurve = pitchBend * pitchBend;
        const float hatBaseHz = 400.0f * expf(hatCurve * LOG_HAT_RATIO);

        // Gentle filter tracking (keeps volume steadier)
        const float hpfHz = 6800.0f * (1.0f + 0.06f * norm);
        const float bpfHz = 9800.0f * (1.0f + 0.05f * norm);

        // --- Voice 2 (FM hats) tuning — reuses pitchBend from above ---
        const float carrier1Hz = 400.0f * expf(pitchBend * LOG_C1_RATIO);
        const float carrier2Hz = 600.0f * expf(pitchBend * LOG_C2_RATIO);
        const float ratio1 = 2.0f * expf(pitchBend * LOG_R1_RATIO);
        const float ratio2 = 4.0f * expf(pitchBend * LOG_R2_RATIO);
        const float modulator1Hz = carrier1Hz * ratio1;
        const float modulator2Hz = carrier2Hz * ratio2;

        // FM depth: slightly more at the top end, but still capped
        const float depth1 = 0.06f + 0.52f * (pitchBend * pitchBend);
        const float depth2 = 0.04f + 0.44f * (pitchBend * pitchBend);

        AudioNoInterrupts();

        // Voice 2 FM hats
        d3W1.frequency(carrier1Hz);
        d3W3.frequency(carrier2Hz);
        d3W2.frequency(modulator1Hz);
        d3W4.frequency(modulator2Hz);
        d3W2.amplitude(depth1);
        d3W4.amplitude(depth2);

        // Voice 1 606 hat oscillator bank
        d3606W1.frequency(hatBaseHz * 1.00f);
        d3606W2.frequency(hatBaseHz * 1.08f);
        d3606W3.frequency(hatBaseHz * 1.17f);
        d3606W4.frequency(hatBaseHz * 1.26f);
        d3606W5.frequency(hatBaseHz * 1.36f);
        d3606W6.frequency(hatBaseHz * 1.48f);
        d3606HPF.frequency(hpfHz);
        d3606BPF.frequency(bpfHz);

        // Voice 3 noise-based hat
        drum3.frequency(carrier1Hz * 0.5f);

        AudioInterrupts();
        break;
      }

    case 17:  // D3 Decay
      {
        float decayMs = map(knobValue, 0, 1023, 100, 1200) * 0.1f;
        d3DecayBase = decayMs;
        applyChokeToDecays();
        break;
      }

    case 18:  // D3 Voice Mix - 3-way
      {
        const int value = constrain(knobValue, 0, 1023);

        // Zone boundaries
        const int PURE1_MAX = int(1023 * 0.06f);
        const int PURE2_MIN = int(1023 * 0.46f);
        const int PURE2_MAX = int(1023 * 0.65f);
        const int PURE3_MIN = int(1023 * 0.94f);

        const float MAX_GAIN = 0.9f;

        // Voice level trims
        const float VOICE1_BOOST = 3.8f;
        const float VOICE2_TRIM = 2.25f;
        const float VOICE3_TRIM = 0.65f;

        float gainVoice1 = 0.0f;
        float gainVoice2 = 0.0f;
        float gainVoice3 = 0.0f;

        // Calculate voice gains based on knob position
        if (value <= PURE1_MAX) {
          gainVoice1 = 1.0f;
        } else if (value < PURE2_MIN) {
          const float blend = float(value - PURE1_MAX) / float(PURE2_MIN - PURE1_MAX);
          gainVoice1 = 1.0f - blend;
          gainVoice2 = blend;
        } else if (value <= PURE2_MAX) {
          gainVoice2 = 1.0f;
        } else if (value < PURE3_MIN) {
          const float blend = float(value - PURE2_MAX) / float(PURE3_MIN - PURE2_MAX);
          gainVoice2 = 1.0f - blend;
          gainVoice3 = blend;
        } else {
          gainVoice3 = 1.0f;
        }

        AudioNoInterrupts();
        d3WfMixer.gain(0, gainVoice1 * MAX_GAIN * VOICE1_BOOST);
        d3WfMixer.gain(1, gainVoice2 * MAX_GAIN * VOICE2_TRIM);
        d3WfMixer.gain(2, gainVoice3 * MAX_GAIN * VOICE3_TRIM);
        AudioInterrupts();
        break;
      }

    case 19:  // D3 Wavefolder Drive
      {
        // True OFF in the first tiny region
        if (knobValue < 10) {
          d3DCwf.amplitude(0.0f);
          AudioNoInterrupts();
          d3Mixer.gain(0, 0.25f);  // dry at default
          d3Mixer.gain(1, 0.0f);   // wavefolder return off
          AudioInterrupts();
          break;
        }

        float norm = normKnob(knobValue);
        norm = (norm - 0.10f) / 0.90f;
        if (norm < 0.0f) norm = 0.0f;
        if (norm > 1.0f) norm = 1.0f;

        // Drive goes 0..0.50 (linear)
        float drive = 0.50f * norm;
        d3DCwf.amplitude(drive);

        // Dry pulls down slightly as drive rises (0.25 → 0.22)
        float dryGain = 0.25f - 0.03f * norm;
        // Wet return ramps up with drive (0.0 → 0.30)
        float wetGain = norm * 0.30f;
        // Loudness comp: gentle to 55%, steeper above (1.0 → 0.934 → 0.684)
        float comp;
        if (norm <= 0.55f) {
          comp = 1.0f - 0.12f * norm;
        } else {
          float base = 1.0f - 0.12f * 0.55f;  // 0.934
          float extra = (norm - 0.55f) / 0.45f; // 0→1 over 55%–100%
          comp = base - 0.25f * extra;
        }
        dryGain *= comp;
        wetGain *= comp;

        AudioNoInterrupts();
        d3Mixer.gain(0, dryGain);  // dry
        d3Mixer.gain(1, wetGain);  // wavefolder return
        AudioInterrupts();
        break;
      }

    case 20:  // D3 Delay Send
      {
        // Capped at 75% to prevent feedback runaway (same as D1/D2)
        float delaySend = map(knobValue, 0, 1023, 0, 75) * 0.01f;
        d3DelaySend = delaySend;
        updateDrumDelayGains();
        break;
      }

    case 21:  // D3 Filter
      {
        float norm = normKnob(knobValue);

        // Cutoff: quadratic curve so the last 20 percent is dramatic
        float normSquared = norm * norm;
        float cutoffHz = 4500.0f + normSquared * (8000.0f - 4500.0f);

        // Resonance: cubic curve so it stays tame, then goes wild
        float resonance = 0.2f + (norm * norm * norm) * (0.9f - 0.2f);

        AudioNoInterrupts();
        d3MasterFilter.frequency(cutoffHz);
        d3MasterFilter.resonance(resonance);
        AudioInterrupts();
        break;
      }

    case 22:  // D3 Accent Pattern
      {
        uint8_t prevMode = d3AltMode;
        d3AltMode = accentModeFromKnob(knobValue);
        d3AccentMask = accentMaskFromMode(d3AltMode);

        // Update cached D3 decay for new accent mode
        d3CachedDecayMs = d3EffectiveBaseDecay();
        {
          AudioNoInterrupts();
          d3AmpEnv.decay(d3CachedDecayMs);
          d3606AmpEnv.decay(d3CachedDecayMs);
          drum3.length(d3CachedDecayMs);
          AudioInterrupts();
        }

        // If mode changed, show the pattern briefly on step LEDs
        if (d3AltMode != prevMode) {
          accentPreviewMask = accentMaskFromMode(d3AltMode);

          uint32_t nowTick;
          noInterrupts();
          nowTick = sysTickMs;  // sysTickMs is ISR-written
          interrupts();

          accentPreviewUntilTick = nowTick + ACCENT_PREVIEW_DURATION_MS;
          accentPreviewActive = true;  // Main-loop only — no guard needed

          updateLEDs();
        }
        break;
      }

    case 23:  // D3 Volume
      {
        float norm = normKnob(knobValue);
        float volume = norm * 5.0f;
        if (volume > 3.5f) volume = 3.5f;

        d3Vol = volume;
        drumMixer.gain(2, d3Vol);
        updateDrumDelayGains();
        break;
      }

      // ========================================================================
      // MASTER EFFECTS (Knobs 24-31)
      // ========================================================================

    case 24:  // Master Delay Time (quantized to tempo)
      {
        int ratioIdx = delayRatioFromKnob(knobValue, bpm);
        float msPerBeat = 60000.0f / bpm;

        float delayMs = msPerBeat * quantizeRatios[ratioIdx];
        if (delayMs > 1400.0f) delayMs = 1400.0f;
        if (delayMs < 0.0f) delayMs = 0.0f;

        masterDelay.delay(0, delayMs);
        break;
      }

    case 25:  // Wavefold Frequency
      {
        float norm = normKnob(knobValue);
        float baseFreq = 40.0f + norm * (1000.0f - 40.0f);

        float sineFreq, sawFreq;

        if (norm <= 0.5f) {
          // 0–50%: sine at baseFreq, saw one octave below (baseFreq / 2)
          sineFreq = baseFreq;
          sawFreq  = baseFreq * 0.5f;
        } else if (norm <= 0.75f) {
          // 50–75%: saw locks to baseFreq, sine diverges up to 2× baseFreq
          float blend = (norm - 0.5f) / 0.25f;               // 0→1 over this zone
          sawFreq  = baseFreq;
          sineFreq = baseFreq * (1.0f + blend);               // 1× → 2× baseFreq
        } else {
          // 75–100%: sine locks to baseFreq, saw diverges up to 4× baseFreq
          float blend = (norm - 0.75f) / 0.25f;              // 0→1 over this zone
          sineFreq = baseFreq;
          sawFreq  = baseFreq * (1.0f + blend * 3.0f);       // 1× → 4× baseFreq
        }

        wfSine.frequency(sineFreq);
        wfSaw.frequency(sawFreq);
        break;
      }

    case 26:  // Master Lowpass Filter
      {
        int freqHz = map(knobValue, 0, 1023, 1000, 7500);
        masterLPFBarX = map(knobValue, 0, 1023, 70, 78);
        masterLowPass.frequency(freqHz);
        break;
      }

    case 27:  // Master Tempo (BPM) — inactive during external clock / PPQN mode
      {
        if (ppqnModeActive) break;     // Don't change BPM while selecting PPQN
        if (transportState == RUN_EXT) break;  // Ignore knob when ext clock drives tempo

        bpm = bpmFromKnob(knobValue);

        // If internal clock is currently running, adjust period without restarting.
        // update() finishes the current interval, then applies the new period —
        // no gap, no stutter.
        if (transportState == RUN_INT) {
          float stepPeriodUs = 15000000.0f / bpm;  // 60M µs / (BPM × 4 subdivisions)
          if (stepPeriodUs < 500.0f) stepPeriodUs = 500.0f;
          stepTimer.update((uint32_t)stepPeriodUs);
        }
        break;
      }

    case 28:  // Master Volume
      {
        float norm = normKnob(knobValue);
        float volume = norm * 2.0f;

        masterNominalGain = volume * 5.0f;
        applyMasterGainFromState();
        break;
      }

    case 29:  // Master Choke Offset
      {
        chokeOffsetMs = chokeOffsetFromKnob(knobValue);
        applyChokeToDecays();
        break;
      }

    case 30:  // Wavefold (master wavefolder drive)
      {
        float norm = normKnob(knobValue);

        // Deadband at bottom 5% — wavefolder fully off
        const float DEADBAND = 0.05f;
        if (norm <= DEADBAND) {
          AudioNoInterrupts();
          wfMixer.gain(0, 0.0f);
          wfMixer.gain(1, 0.0f);
          masterWfComp = 1.0f;
          masterMixer.gain(0, 1.0f);  // dry at unity
          masterMixer.gain(1, 0.0f);  // wavefolder return off
          AudioInterrupts();

          applyMasterGainFromState();
          break;
        }

        // Remap past deadband to 0–1
        float active = (norm - DEADBAND) / (1.0f - DEADBAND);
        if (active > 1.0f) active = 1.0f;

        // Both sine and saw rise together, quadratic ramp.
        // Plateau after 60% — cap the oscillator drive level.
        float activeSq = active * active;
        float oscActive = (active <= 0.6f) ? active : 0.6f;
        float oscSq = oscActive * oscActive;
        float sineGain = oscSq * 0.55f;
        float sawGain  = oscSq * 0.55f;

        // Drive fraction for compensation (0→1)
        float drive = activeSq;

        // Dry bus: normal pull-down up to 65%, then roll off to 50% of normal
        float dryBase = 1.0f - 0.08f * drive;
        if (active > 0.65f) {
          float rolloff = (active - 0.65f) / (1.0f - 0.65f);  // 0→1 over 65%–100%
          dryBase *= 1.0f - 0.5f * rolloff;                    // down to 50%
        }
        float dryLevel = dryBase;

        // Wavefolder return: ramp up more to compensate for dry rolloff (0.32 → 0.74)
        float wfReturn = 0.32f + 0.42f * drive;

        // Loudness compensation — normalize so dry+wet never exceeds unity
        float sum = dryLevel + wfReturn;
        float comp = (sum > 1.0f) ? 1.0f / sum : 1.0f;
        masterWfComp = comp;

        AudioNoInterrupts();
        wfMixer.gain(0, sineGain);
        wfMixer.gain(1, sawGain);
        masterMixer.gain(0, dryLevel);
        masterMixer.gain(1, wfReturn);
        AudioInterrupts();

        applyMasterGainFromState();
        break;
      }

    case 31:  // Master Delay Mix/Feedback
      {
        float norm = normKnob(knobValue);

        // Dead band below 5% — delay fully OFF
        if (norm <= 0.05f) {
          delayAmp.gain(0.0f);
          masterMixer.gain(2, 0.0f);  // delay return
        } else {
          // Remap 5%-100% → 0-1, then use sqrt curve for more level at low knob
          float blend = (norm - 0.05f) / 0.95f;
          float shaped = sqrtf(blend);  // sqrt gives more audible range at low settings
          float level = 0.15f + shaped * 0.90f;  // 15% floor, 5% louder max (1.05)
          delayAmp.gain(level * 2.0f);
          masterMixer.gain(2, level);
        }

        // Feedback amount (squared curve for finer low-end control), capped at 0.4
        float feedback = norm * norm * 0.4f;
        delayMixer.gain(3, feedback);
        break;
      }

    default:
      break;
  }
}

// initialization from hardware

void initKnobsFromHardware() {
  // Read all knobs, settle filters, apply to engine, and store boot values.
  // Boot-lock prevents ADC drift from changing params until the user moves a knob.
  for (byte idx = 0; idx < knobCount; idx++) {
    int rawValue = readKnobRaw(idx);

    // Update filter multiple times to settle it
    for (int i = 0; i < 4; i++) {
      analog[idx]->update(rawValue);
    }

    knobBootValue[idx] = rawValue;
    knobUnlocked[idx] = false;

    applyKnobToEngine(idx, rawValue);
  }
}

// OPTIMIZATION: round-robin knob scanning — reads 8 knobs per loop iteration
// instead of all 32, reducing per-loop delayMicroseconds overhead by 4x
void updateKnobs() {
  static uint8_t knobScanGroup = 0;
  byte start = knobScanGroup * 8;
  byte end = start + 8;

  for (byte idx = start; idx < end; idx++) {
    int rawValue = readKnobRaw(idx);
    analog[idx]->update(rawValue);

    if (analog[idx]->hasChanged()) {
      int knobValue = analog[idx]->getValue();

      // Boot-lock: ignore small ADC drift until the user intentionally moves
      // the knob past the unlock threshold from its power-on position.
      if (!knobUnlocked[idx]) {
        int diff = knobValue - knobBootValue[idx];
        if (diff < 0) diff = -diff;
        if (diff < KNOB_UNLOCK_THRESHOLD) continue;
        knobUnlocked[idx] = true;
      }

      updateParameterDisplay(idx, knobValue);
      applyKnobToEngine(idx, knobValue);
    }
  }

  knobScanGroup = (knobScanGroup + 1) & 3;  // 0,1,2,3 → cycle through 4 groups
}

// UI helpers

static inline void drawCaretRail(int x, int y, int w, int h, int caretX) {
  display.drawRect(x, y, w, h, 1);
  int cx = constrain(caretX, x + 1, x + w - 2);
  display.drawLine(cx, y - 2, cx, y + h + 2, 1);
}

static inline void labelAtCenter(const char* text, int centerX, int y) {
  int16_t x1, y1;
  uint16_t w, h;
  display.getTextBounds(text, 0, 0, &x1, &y1, &w, &h);
  int x = centerX - (w / 2);
  drawOutlinedText(x, y, text);
}

void renderVoiceRails() {
  // Rail displayed alongside scope: label text at y=23, rail bar at y=44
  const int railX = 6;
  const int railY = 44;
  const int railW = 116;
  const int railH = 10;
  const int labelY = 23;

  display.setTextSize(1);

  if (activeRail == RAIL_D1_SHAPE) {
    drawCaretRail(railX, railY, railW, railH, railX + (int)(uiMixD1Shape * railW));
    int third = railW / 3;
    labelAtCenter("SIN", railX + third * 0 + third / 2, labelY);
    labelAtCenter("SAW", railX + third * 1 + third / 2, labelY);
    labelAtCenter("SQR", railX + third * 2 + third / 2, labelY);
    int zone = (uiMixD1Shape < 1.0f / 3.0f)   ? 0
               : (uiMixD1Shape < 2.0f / 3.0f) ? 1
                                              : 2;
    int zx = railX + zone * third + 1;
    int zw = third - 2;
    display.fillRect(zx, railY + 1, zw, railH - 2, 1);
  }

  if (activeRail == RAIL_D2_VOICE) {
    int caret = railX + (int)(uiMixD2Voice * railW);
    drawCaretRail(railX, railY, railW, railH, caret);
    labelAtCenter("CLAP", railX + 14, labelY);
    labelAtCenter("SNARE", railX + railW - 14, labelY);
    int fillW = max(1, caret - railX);
    display.fillRect(railX + 1, railY + 1, fillW - 2, railH - 2, 1);
  }

  if (activeRail == RAIL_D3_VOICE) {
    drawCaretRail(railX, railY, railW, railH, railX + (int)(uiMixD3Voice * railW));
    int third = railW / 3;
    labelAtCenter("1", railX + third * 0 + third / 2, labelY);
    labelAtCenter("2", railX + third * 1 + third / 2, labelY);
    labelAtCenter("3", railX + third * 2 + third / 2, labelY);
    int zone = (uiMixD3Voice < 1.0f / 3.0f)   ? 0
               : (uiMixD3Voice < 2.0f / 3.0f) ? 1
                                              : 2;
    int zx = railX + zone * third + 1;
    int zw = third - 2;
    display.fillRect(zx, railY + 1, zw, railH - 2, 1);
  }
}

// Draw text with 1-pixel black outline for readability on top of the scope waveform.
// Uses 4 cardinal offsets (N/S/E/W) instead of 8 — half the draws, visually identical at 1px.
void drawOutlinedText(int x, int y, const char* text) {
  display.setTextColor(0);        // black outline
  display.setCursor(x, y - 1); display.print(text);  // N
  display.setCursor(x, y + 1); display.print(text);  // S
  display.setCursor(x - 1, y); display.print(text);  // W
  display.setCursor(x + 1, y); display.print(text);  // E
  display.setTextColor(1);        // white foreground
  display.setCursor(x, y);
  display.print(text);
}

// OLED drawing
void updateDisplay() {
  // Snapshot time first
  uint32_t nowMs;
  noInterrupts();
  nowMs = sysTickMs;
  interrupts();

  // PPQN selection mode — full-screen takeover, skip normal UI
  if (ppqnModeActive) {
    display.clearDisplay();
    display.setFont(NULL);
    display.setTextColor(1);
    display.setTextWrap(false);

    display.setTextSize(1);
    display.setCursor(20, 0);
    display.print("CLOCK MODE");

    display.setCursor(4, 16);
    display.print("TURN BPM TO CHANGE");

    display.setTextSize(2);
    display.setCursor(16, 38);
    display.print("PPQN:");
    display.print(ppqnModeSelection);

    display.display();

    // Update watchdog timestamp so OLED reinit doesn't fire during PPQN mode
    noInterrupts();
    lastFrameDrawTick = nowMs;
    interrupts();
    return;
  }

  // Snapshot all state we will render so a single frame is coherent
  float bpmSnap;
  uint8_t trackSnap;
  int lpfSnap;
  uint8_t slotSnap;
  bool playingSnap;
  uint32_t overlayStartSnap;
  uint8_t railSnap;
  char param1Snap[24];
  char param2Snap[24];

  // Snapshot ISR-shared state with interrupts disabled
  noInterrupts();
  playingSnap = sequencePlaying;
  interrupts();

  // Main-loop only — no ISR access, safe without guards
  bpmSnap = bpm;
  trackSnap = activeTrack;
  lpfSnap = masterLPFBarX;
  slotSnap = activeSaveSlot;
  overlayStartSnap = parameterOverlayStartTick;
  railSnap = activeRail;

  strncpy(param1Snap, displayParameter1, sizeof(param1Snap) - 1);
  param1Snap[sizeof(param1Snap) - 1] = 0;

  strncpy(param2Snap, displayParameter2, sizeof(param2Snap) - 1);
  param2Snap[sizeof(param2Snap) - 1] = 0;

  // Overlay state
  bool overlayActiveNow =
    ((uint32_t)(nowMs - overlayStartSnap) < PARAMETER_OVERLAY_DURATION_MS);

  display.clearDisplay();

  // Setup text defaults
  display.setFont(NULL);
  display.setTextColor(1);
  display.setTextSize(1);
  display.setTextWrap(false);

  // Double-thick horizontal divider (y=19..20) and left vertical border (x=0..1)
  display.drawLine(1, 21, 1, 63, 1);
  display.drawLine(1, 20, 127, 20, 1);
  display.drawLine(0, 63, 0, 20, 1);
  display.drawLine(1, 19, 127, 19, 1);

  // BPM / EXT clock state — always show one decimal place
  display.setCursor(0, 0);
  if (transportState == RUN_EXT) {
    display.print("EXT");
    display.setCursor(0, 10);
    if (extBpmDisplay > 0) {
      display.print(extBpmDisplay, 1);
    }
  } else {
    display.print("BPM");
    display.setCursor(0, 10);
    display.print(bpmSnap, 1);
  }

  // Track
  display.setCursor(37, 0);
  display.print("TRK");
  display.setCursor(40, 10);
  if (trackSnap == TRACK_D1) {
    display.print("D1");
  } else if (trackSnap == TRACK_D2) {
    display.print("D2");
  } else {
    display.print("D3");
  }

  // LPF
  display.setCursor(62, 0);
  display.print("LPF");
  if (lpfSnap >= 78) {
    display.setCursor(62, 10);
    display.print("OFF");
  } else {
    int barEnd = lpfSnap;
    display.drawLine(62, 10, barEnd, 10, 1);
    display.drawLine(barEnd + 4, 16, barEnd + 1, 11, 1);
  }

  // Memory slot
  display.setCursor(90, 0);
  display.print("MEM");
  display.setCursor(92, 10);
  display.print(slotSnap);

  // Play/Stop icon
  if (playingSnap) {
    display.drawBitmap(116, 4, image_play_bits, 10, 10, 1);
  } else {
    display.drawBitmap(116, 4, image_stop_bits, 10, 10, 1);
  }

  // Oscilloscope — always drawn (not replaced by overlay)
  drawScopeWaveform(2, 22, SCOPE_DISPLAY_WIDTH, SCOPE_DISPLAY_HEIGHT);

  // Parameter overlay at bottom of screen (on top of scope)
  if (overlayActiveNow) {
    if (railSnap == RAIL_NONE) {
      // Normal parameter: name left-aligned, value right-aligned at bottom
      // Outlined text keeps scope waveform visible behind the overlay
      display.setTextSize(1);
      const int bottomY = 56;
      if (param1Snap[0]) {
        drawOutlinedText(5, bottomY, param1Snap);
      }
      if (param2Snap[0]) {
        int16_t x1, y1;
        uint16_t w2, h2;
        display.getTextBounds(param2Snap, 0, 0, &x1, &y1, &w2, &h2);
        drawOutlinedText(128 - w2 - 2, bottomY, param2Snap);
      }
    } else {
      // Voice rail only — rail graphic already contains labels, no extra text
      renderVoiceRails();
    }
  }

  display.display();

  // Update OLED watchdog timestamp only after a successful draw
  noInterrupts();
  lastFrameDrawTick = nowMs;
  interrupts();
}