// DrumSynth

#include <Arduino.h>
#include <Mux.h>
#include <ResponsiveAnalogRead.h>
#include <ShiftRegister74HC595.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SH110X.h>
#include <EEPROM.h>

// Audio objects: names generated by the Teensy Audio Design Tool (https://www.pjrc.com/teensy/gui/).
// Prefix convention: d1/d2/d3 = drum voice, clap/snare = sub-voice, master = output stage.
#include "audiotool.h"
#include "audio_init.h"
#include "bitmaps.h"
#include "hw_setup.h"

// Forward declaration for Arduino auto-prototype generation.
// Full definition is in the button state machine section below.
struct ButtonHandler;

// FIRMWARE_VERSION auto-generated from compile date (__DATE__).
// Format: "MM.DD.YY" (e.g., "03.04.26" for March 4, 2026).
// Uses a constexpr lookup to convert the __DATE__ month abbreviation to a 2-digit number.
// __DATE__ format: "Mar  4 2026" (month abbreviation, day, 4-digit year)
// Months: Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
// Ambiguous firsts resolved by [1] or [2]: J+a→Jan, J+n→Jun, J+l→Jul; M+r→Mar, M+y→May; A+p→Apr, A+u→Aug
static constexpr int fwMonth =
    (__DATE__[0] == 'J' && __DATE__[1] == 'a') ? 1  :
    (__DATE__[0] == 'F')                        ? 2  :
    (__DATE__[0] == 'M' && __DATE__[2] == 'r') ? 3  :
    (__DATE__[0] == 'A' && __DATE__[1] == 'p') ? 4  :
    (__DATE__[0] == 'M' && __DATE__[2] == 'y') ? 5  :
    (__DATE__[0] == 'J' && __DATE__[2] == 'n') ? 6  :
    (__DATE__[0] == 'J' && __DATE__[2] == 'l') ? 7  :
    (__DATE__[0] == 'A' && __DATE__[1] == 'u') ? 8  :
    (__DATE__[0] == 'S')                        ? 9  :
    (__DATE__[0] == 'O')                        ? 10 :
    (__DATE__[0] == 'N')                        ? 11 :
    (__DATE__[0] == 'D')                        ? 12 : 0;
static constexpr int fwDay =
    (__DATE__[4] == ' ') ? (__DATE__[5] - '0')
                         : (__DATE__[4] - '0') * 10 + (__DATE__[5] - '0');
static constexpr int fwYear = (__DATE__[9] - '0') * 10 + (__DATE__[10] - '0');
// __TIME__ format: "14:34:05" (HH:MM:SS, always 8 chars)
static constexpr int fwHour = (__TIME__[0] - '0') * 10 + (__TIME__[1] - '0');
static constexpr int fwMin  = (__TIME__[3] - '0') * 10 + (__TIME__[4] - '0');

static constexpr const char* FIRMWARE_VERSION   = "1.05";
static constexpr const char* FIRMWARE_DATE_FMT  = "%02d.%02d.%02d - %02d:%02d";
#define FIRMWARE_DATE_ARGS fwMonth, fwDay, fwYear, fwHour, fwMin  // macro: expands to variadic args

// Track enum — declared early so Arduino auto-prototypes can reference it
enum Track : uint8_t {
  TRACK_D1 = 0,
  TRACK_D2 = 1,
  TRACK_D3 = 2
};

// overlay and debounce timing
static constexpr uint16_t PARAMETER_OVERLAY_DURATION_MS = 500;
static constexpr uint16_t STEP_DEBOUNCE_MS = 10;        // 10ms — fast response for sync (step buttons only)
static constexpr uint8_t  MONOBASS_DEBOUNCE_MS = 10;   // 10ms — reliable debounce with fast trill response
static bool monoBassKeyEvent = false;                   // set by handleMonoBassButton() to skip next OLED frame
static constexpr uint16_t PLAY_DEBOUNCE_MS = 2;       // Play button: minimal debounce for tight sync
static constexpr uint16_t BUTTON_DEBOUNCE_MS = 25;    // All other buttons: standard debounce
static constexpr float    WF_DEADBAND = 0.03f;        // wavefolder off below 3% — used by all wavefolder cases (11, 19, 30)

// D3 accent LED preview state — Main-loop only, no ISR access
struct AccentPreview {
  bool active = false;
  uint32_t startTick = 0;
  uint16_t mask = 0;  // bit15 = step0 ... bit0 = step15
};
AccentPreview accentPreview;
static constexpr uint16_t ACCENT_PREVIEW_DURATION_MS = 1500;

// PPQN selection mode state — main-loop only
bool ppqnModeActive = false;
uint32_t ppqnModeLastActivityTick = 0;  // Last knob/button interaction
uint8_t ppqnModeSelection = 2;          // Currently selected value in mode
static constexpr uint32_t PPQN_MODE_TIMEOUT_MS = 5000;
static constexpr uint32_t PPQN_LONG_PRESS_MS = 1500;

// PPQN options table
static constexpr uint8_t PPQN_OPTIONS[] = {1, 2, 4, 8, 24, 48, 96};
static constexpr uint8_t PPQN_OPTION_COUNT = sizeof(PPQN_OPTIONS) / sizeof(PPQN_OPTIONS[0]);

// D1 chroma mode state — main-loop only
bool d1ChromaMode = false;
static constexpr uint32_t D1_CHROMA_LONG_PRESS_MS = 1500;

// MONOBASS mode — see monobass.h (included after forward declarations).

// D2 chroma mode — latching toggle via D2 button hold
bool d2ChromaMode = false;
static constexpr uint32_t D2_CHROMA_LONG_PRESS_MS = 1500;

// D3 chroma mode — latching toggle via D3 button hold
bool d3ChromaMode = false;
static constexpr uint32_t D3_CHROMA_LONG_PRESS_MS = 1500;

// Wavefolder CHROMA mode — latching toggle via PLAY button hold
bool wfChromaMode = false;
static constexpr uint32_t WF_CHROMA_LONG_PRESS_MS = 1500;

static constexpr uint32_t CHROMA_STEP_HOLD_MS = 300;  // Hold step button this long to select note
int8_t d1ChromaHeldStep = -1;  // Which step button is held (-1 = none)
int8_t d2ChromaHeldStep = -1;  // Which step is in D2 chroma note-select (-1 = none)
int8_t d3ChromaHeldStep = -1;  // Which step is in D3 chroma note-select (-1 = none)

// Per-step MIDI note for D1 chroma (A1=33 to A4=69, 36 semitones)
// Default C2 = MIDI 36
uint8_t d1ChromaNote[numSteps] = {
  36,36,36,36, 36,36,36,36, 36,36,36,36, 36,36,36,36
};

// Per-step MIDI note for D2 chroma (A2=45 to A4=69, 24 semitones)
// Default C3 = MIDI 48
uint8_t d2ChromaNote[numSteps] = {
  48,48,48,48, 48,48,48,48, 48,48,48,48, 48,48,48,48
};

// Per-step MIDI note for D3 chroma (C3=48 to C6=84, 36 semitones)
// Default C3 = MIDI 48
uint8_t d3ChromaNote[numSteps] = {
  48,48,48,48, 48,48,48,48, 48,48,48,48, 48,48,48,48
};

// ============================================================================
//  Sequences
// ============================================================================

uint8_t d1Sequence[numSteps] = {
  0, 0, 0, 0,
  0, 0, 0, 0,
  0, 0, 0, 0,
  0, 0, 0, 0
};

uint8_t d2Sequence[numSteps] = {
  0, 0, 0, 0,
  0, 0, 0, 0,
  0, 0, 0, 0,
  0, 0, 0, 0
};

uint8_t d3Sequence[numSteps] = {
  0, 0, 0, 0,
  0, 0, 0, 0,
  0, 0, 0, 0,
  0, 0, 0, 0
};

// ============================================================================
//  Timing, Tempo, and Transport
// ============================================================================

IntervalTimer sysTickTimer;
IntervalTimer stepTimer;

volatile uint32_t sysTickMs = 0;  // Written by sysTickISR, read by main loop

// bpm: main-loop only — not accessed from any ISR. rearmStepTimer() is only
// called from setTransport() and setup(), both main-loop context.
float bpm = 120.0f;
// currentStep: ISR-written (stepISR, externalClockISR, subdivTimerCallback),
// main loop reads. See concurrency contract in ext_sync.h.
volatile uint8_t currentStep = 0;

// Three states: internal clock, external clock, or stopped
enum TransportState : uint8_t {
  STOPPED   = 0,
  RUN_INT   = 1,   // Internal timer drives steps
  RUN_EXT   = 2    // External pulse ISR drives steps
};

volatile TransportState transportState = STOPPED;  // Read by stepISR, externalClockISR
volatile bool sequencePlaying = false;     // Read by stepISR, externalClockISR
volatile bool armed = false;              // PLAY sets true; ISR counts down then fires step 0
volatile uint16_t armPulseCountdown = 0;  // Pulses remaining before step 0 fires (one full cycle)

// PPQN for external clock — loaded from EEPROM at boot, selectable via UI.
// ISR reads (externalClockISR), main loop writes (PPQN selection mode).
// uint8_t is atomic on ARM Cortex-M7 — no interrupt guards needed.
static constexpr uint8_t PPQN_DEFAULT = 2;  // shared with eeprom.h fallback
volatile uint8_t ppqn = PPQN_DEFAULT;

// Minimum interval between retriggering the same voice (µs).
// Avoids noteOff() killing a just-triggered envelope when two steps fire
// in rapid succession (e.g. skip-ahead fires step N then subdivision fires N+1).
static constexpr uint32_t MIN_RETRIGGER_US = 1500;

// Per-voice retrigger timestamps — main loop only (via playSequenceCore)
uint32_t lastD1TriggerUs = 0;
uint32_t lastD2TriggerUs = 0;
uint32_t lastD3TriggerUs = 0;

// ---------------------------------------------------------------------------
// Mid-file includes: These headers define functions/ISRs that reference globals
// declared above. Arduino IDE compiles .ino as a single translation unit, so
// these headers act as inline code segments rather than independent modules.
// ---------------------------------------------------------------------------

// External clock sync — ISRs, state variables, glitch filter, EMA, helpers
// (depends on: TransportState, stepTimer, bpm, ppqn, playSequenceCore, currentStep)
#include "ext_sync.h"

// OLED watchdog and frame timing
// Written: main loop (updateDisplay). Read: sysTickISR (watchdog), main loop (frame limiter).
volatile uint32_t lastFrameDrawTick = 0;
static constexpr uint32_t OLED_WATCHDOG_TIMEOUT_MS = 750;
static constexpr uint32_t OLED_FRAME_INTERVAL_MS = 42;        // ~24 fps
static constexpr uint32_t OLED_FRAME_INTERVAL_EXT_MS = 100;   // ~10 fps (ext sync — reduces SPI blocking)
static constexpr uint32_t OLED_SUBDIV_GUARD_US = 30000;      // Skip OLED frame if subdivision due within 30ms
volatile bool requestOledReinit = false;  // Set by sysTickISR, cleared by main loop
uint32_t displayBlockedUntilTick = 0;       // Suppress OLED push after drop-in (main-loop only)

// Oscilloscope — scope buffer, updateScopeData(), drawScopeWaveform()
#include "oscilloscope.h"

// ============================================================================
//  Decay and Envelope State
// ============================================================================

// Base decay values (raw knob position, before choke offset)
float d1DecayBase = 75.0f;
float d2DecayBase = 75.0f;
float d2DecayNorm = 0.0f;  // 0–1 knob position, used by clap curves
float d3DecayBase = 25.0f;

// Effective decays (base + choke offset, updated by applyChokeToDecays)
float d1EffectiveDecay = 75.0f;
float d2ClapEffectiveDecay = 60.0f;  // Derived from d2DecayBase via normalized mapping
float d3EffectiveDecay = 25.0f;       // Includes accent boost when accent mode active

// Global choke offset
int chokeOffsetMs = 0;
int chokeDisplayPercent = 0;  // -100 to +100, for top bar and overlay display

// D1 envelope params
static constexpr float D1_ATTACK_MS = 0.5f;  // 808-style instant punch — fixed, not knob-controlled
float d1CachedHoldMs = 56.25f;               // scales with decay; see updateD1HoldCache()

// ============================================================================
//  Display State — Main-loop only, no ISR access
// ============================================================================

// Parameter overlay text
char displayParameter1[24] = "";
char displayParameter2[24] = "";
uint32_t parameterOverlayStartTick = 0;

// Voice rail caret positions
float uiMixD1Shape = 0.0f;
float uiMixD2Voice = 0.0f;
float uiMixD3Voice = 0.0f;

enum RailMode : uint8_t {
  RAIL_NONE = 0,
  RAIL_D1_SHAPE,
  RAIL_D2_VOICE,
  RAIL_D3_VOICE
};

RailMode activeRail = RAIL_NONE;

// EEPROM persistence — structs, constants, save/load functions
// (must be included after sequences, ppqn, PPQN_OPTIONS, RailMode, UI overlay vars)
#include "eeprom.h"

// delay ratios (in quarter-note units)
static constexpr float quantizeRatios[] = {
  0.25f,        // 1/4  of a quarter  = 1/16
  0.33333333f,  // 1/3  of a quarter  = 1/8T
  0.375f,       // 3/8  of a quarter  = 1/16.
  0.5f,         // 1/2  of a quarter  = 1/8
  0.66666667f,  // 2/3  of a quarter = 1/4T
  0.75f,        // 3/4  of a quarter = 1/8.
  1.0f,         // 1    quarter      = 1/4
  1.25f,        // 5/4  quarters     = 5/16
  1.33333333f,  // 4/3  quarters     = 1/2T
  1.5f,         // 3/2  quarters     = 1/4.
  2.0f,         // 2    quarters     = 1/2
  2.5f,         // 5/2  quarters     = 5/8
  3.0f          // 3    quarters     = 1/2.
};

static constexpr const char* ratioLabels[] = {
  "1/16",
  "1/8T",
  "1/16.",
  "1/8",
  "1/4T",
  "1/8.",
  "1/4",
  "5/16",
  "1/2T",
  "1/4.",
  "1/2",
  "5/8",
  "1/2."
};

static constexpr int NUM_RATIOS = sizeof(quantizeRatios) / sizeof(quantizeRatios[0]);
static_assert(sizeof(ratioLabels) / sizeof(ratioLabels[0]) == NUM_RATIOS,
              "ratioLabels must match quantizeRatios count");

// master gain
float masterNominalGain = 1.0f;

// drum levels
float d1Volume = 0.65f;
float d2Volume = 1.25f;
float d3Volume = 0.75f;

// delay sends
float d1DelaySend = 0.0f;
float d2DelaySend = 0.0f;
float d3DelaySend = 0.0f;

// accents
enum AccentMode : uint8_t {
  ACCENT_OFF = 0,
  ACCENT_PICKUP,
  ACCENT_HALF,
  ACCENT_QUARTER,
  ACCENT_EIGHTH_DOWN,
  ACCENT_EIGHTH_UP,
  ACCENT_BOSSA,
  ACCENT_OFFBEAT,
  ACCENT_CLAVE,
  ACCENT_THREE_TWO,
  ACCENT_PAIRS,
  ACCENT_TRIPLET,
  ACCENT_DOTTED_EIGHTH,
  ACCENT_BACK_HALF,
  ACCENT_CASCADE
};

static constexpr const char* accentNames[] = {
  "OFF", "PICKUP", "HALF", "QUARTER", "8TH DN", "8TH UP",
  "BOSSA", "OFFBEAT", "CLAVE", "3-2", "PAIRS",
  "TRIPLET", "DOT 8TH", "BACK 1/2", "CASCADE"
};
static_assert(sizeof(accentNames) / sizeof(accentNames[0]) == ACCENT_CASCADE + 1,
              "accentNames must match AccentMode enum count");

uint8_t d3AccentMode = ACCENT_OFF;
uint16_t d3AccentMask = 0;  // Cached: accentMaskFromMode(d3AccentMode), updated on accent knob change

// Accented hi-hat decay multiplier (2.5x longer decay on accent steps)
static constexpr float D3_ACCENT_FACTOR = 2.5f;


Track activeTrack = TRACK_D1;  // Main-loop only — no ISR access

// knob smoothing
ResponsiveAnalogRead* analog[knobCount];

// Knob precision tuning — adjust on hardware (testPotResolution branch)
static constexpr uint8_t  KNOB_HW_AVG          = 8;     // Hardware ADC averaging (1, 4, 8, 16, 32)
static constexpr uint8_t  KNOB_MUX_SETTLE_US   = 10;    // Mux settle time (µs) after channel switch (was 5)
static constexpr uint8_t  KNOB_OVERSAMPLE      = 4;     // Software ADC reads to average (1 = none, 4 = 2× noise reduction)
static constexpr int      KNOB_ACTIVITY_THRESH  = 10;    // RAR activity threshold (was 36; lower = finer, noisier)
static constexpr float    KNOB_SNAP_MULTI       = 0.01f; // RAR snap multiplier (default 0.01; higher = faster tracking)

// Boot-lock: suppress knob updates until user intentionally moves a knob.
// Prevents ADC drift on power-up from changing parameter values.
static int16_t knobBootValue[knobCount];   // ADC value at boot (after filter settles)
static bool    knobUnlocked[knobCount];    // true once the user has moved this knob
static constexpr int KNOB_UNLOCK_THRESHOLD = 10;  // ADC counts of intentional movement

// helpers
static inline float mapFloat(int inputValue, int inMin, int inMax, float outMin, float outMax) {
  if (inMax == inMin) return outMin;  // guard: avoid divide-by-zero
  return outMin + (outMax - outMin) * float(inputValue - inMin) / float(inMax - inMin);
}

static inline float normalizeKnob(int rawKnobValue) {
  return float(rawKnobValue) / 1023.0f;
}

// D1 osc and pitch
float d1BaseFreq = 100.0f;
float d1FreqBeforeChroma = 100.0f;  // saved on D1 chroma entry, restored on exit

// D1 chroma envelope filter state (snap knob repurposed, mirrors MONOBASS logic)
float d1ChromaEnvFiltDepth = 0.0f;    // 0–1 from snap knob
float d1ChromaEnvFiltBaseHz = 100.0f; // resting cutoff cached from body knob
uint32_t d1ChromaEnvFiltTrigger = 0;  // sysTickMs of last D1 trigger in chroma mode

void applyD1Freq() {
  AudioNoInterrupts();
  d1OscSine.frequency(d1BaseFreq);
  d1OscSaw.frequency(d1BaseFreq);
  d1OscSquare.frequency(d1BaseFreq);
  AudioInterrupts();
}

// choke mapping helper
static inline int chokeOffsetFromKnob(int knobVal) {
  const int CENTER = 512;
  const int DEADBAND = 80;
  const int MAX_NEG = -55;
  const int MAX_POS = 150;

  // Deadband: center ±80 ADC counts → offset 0ms
  if (knobVal >= CENTER - DEADBAND && knobVal <= CENTER + DEADBAND) {
    return 0;
  }

  // Left of deadband: full CCW → -55ms
  if (knobVal < CENTER - DEADBAND) {
    int lowEnd = CENTER - DEADBAND;  // also the full range [0, lowEnd]
    float blend = float(lowEnd - knobVal) / float(lowEnd);
    return (int)(MAX_NEG * blend);
  }

  // Right of deadband: full CW → +150ms
  int highStart = CENTER + DEADBAND;
  float blend = float(knobVal - highStart) / float(1023 - highStart);
  return (int)(MAX_POS * blend);
}

// D3 effective decay (includes choke and accent boost, capped at 250ms)
static inline float computeD3Decay() {
  float base = d3DecayBase + chokeOffsetMs;
  if (base < 7.0f) base = 7.0f;
  if (d3AccentMode != ACCENT_OFF) base += 7.0f;
  if (base > 250.0f) base = 250.0f;
  return base;
}


// sequence routing
uint8_t* sequenceForTrack(Track t) {
  switch (t) {
    case TRACK_D1: return d1Sequence;
    case TRACK_D2: return d2Sequence;
    case TRACK_D3: return d3Sequence;
    default:       return d1Sequence;
  }
}

// forward declarations
void updateOtherButtons();
void updateStepButtons();
void updateLEDs();
void updateDisplay();
void selectTrack(Track t);
void playSequence();
void playSequenceCore(uint8_t step);
void triggerD1();
void triggerD2();
void triggerD3(uint8_t step);
int readKnobRaw(uint8_t idx);
void updateParameterDisplay(uint8_t idx, int knobValue);
void applyKnobToEngine(uint8_t idx, int knobValue);
void updateKnobs();
void setTransport(TransportState s);
void updateDrumDelayGains();
void initKnobsFromHardware();
void applyMasterGain();
void handlePlayStop();
void applyD1Decay();
void applyD2Decay();
void applyD3Decay();
void applyChokeToDecays();
void drawOutlinedText(int x, int y, const char* text);

// MONOBASS — struct, constants, entry/exit, keyboard handler, display renderer.
// Included here because it depends on forward declarations above and state
// variables like D1_ATTACK_MS, TransportState, d1EffectiveDecay, etc.
#include "monobass.h"
MonoBassState monoBass;

// Accent pattern bitmask — single source of truth for all 15 accent modes (OFF + 14 patterns).
// Bit 15 = step 0, bit 0 = step 15.  Used by triggerD3() and LED preview.
static inline uint16_t accentMaskFromMode(uint8_t mode) {
  switch (mode) {
    case ACCENT_PICKUP:    return 0b0000000000000010;  // step 14 only
    case ACCENT_HALF:      return 0b1000000010000000;  // steps 0, 8
    case ACCENT_QUARTER:   return 0b1000100010001000;  // steps 0, 4, 8, 12
    case ACCENT_EIGHTH_DOWN:   return 0b1010101010101010;  // even steps (downbeat eighths)
    case ACCENT_EIGHTH_UP:     return 0b0101010101010101;  // odd steps (upbeat eighths)
    case ACCENT_BOSSA:         return 0b1001001000100100;  // steps 0, 3, 6, 10, 13
    case ACCENT_OFFBEAT:       return 0b0010001000100010;  // offbeat quarter (steps 2, 6, 10, 14)
    case ACCENT_CLAVE:         return 0b1001001000101000;  // steps 0, 3, 6, 10, 12
    case ACCENT_THREE_TWO:     return 0b1001001010010010;  // steps 0, 3, 6, 8, 11, 14
    case ACCENT_PAIRS:         return 0b0011001100110011;  // pairs (steps 2-3, 6-7, 10-11, 14-15)
    case ACCENT_TRIPLET:       return 0b0010010010010010;  // 3-step grouping (steps 2, 5, 8, 11, 14)
    case ACCENT_DOTTED_EIGHTH: return 0b1001001001001001;  // dotted eighth (steps 0, 3, 6, 9, 12, 15)
    case ACCENT_BACK_HALF:     return 0b0000111100001111;  // back halves (steps 4-7, 12-15)
    case ACCENT_CASCADE:       return 0b1010010010100101;  // steps 0, 2, 5, 8, 10, 13, 15
    default: return 0;
  }
}

// ============================================================================
//  Timers and Interrupts
// ============================================================================

void sysTickISR() {
  uint32_t now = sysTickMs + 1;
  sysTickMs = now;

  // Aligned 32-bit reads are atomic on ARM Cortex-M7
  if ((uint32_t)(now - lastFrameDrawTick) > OLED_WATCHDOG_TIMEOUT_MS) {
    requestOledReinit = true;
  }
}

// ============================================================================
//  Audio Helpers
// ============================================================================

void updateDrumDelayGains() {
  // Decouple delay sends from the drum output levels.
  // This keeps delay tails and throws consistent even if a drum is turned down or muted.

  float s1 = d1DelaySend * 0.6f;   // D1 tapped post-amp — scale down to match D2 level
  float s2 = d2DelaySend;          // D2 tapped at snareClapMixer — reference level
  float s3 = d3DelaySend * 1.75f;  // D3 tapped post-filter (quieter than D2) — 1.75× compensates for filter attenuation

  // Keep the combined delay input from getting too hot.
  // (Prevents clipping when multiple sends are high at once.)
  const float SEND_SUM_TARGET = 0.90f;
  float sum = s1 + s2 + s3;
  if (sum > SEND_SUM_TARGET) {
    float scaleFactor = SEND_SUM_TARGET / sum;
    s1 *= scaleFactor;
    s2 *= scaleFactor;
    s3 *= scaleFactor;
  }

  AudioNoInterrupts();
  delaySendMixer.gain(0, s1);
  delaySendMixer.gain(1, s2);
  delaySendMixer.gain(2, s3);
  AudioInterrupts();
}

void applyMasterGain() {
  AudioNoInterrupts();
  masterAmp.gain(masterNominalGain);
  AudioInterrupts();
}

// Recompute cached D1 hold time (scales with decay).
// Call on choke or decay change.
static inline void updateD1HoldCache() {
  d1CachedHoldMs = d1EffectiveDecay * 0.75f;
}

// choke application on all relevant decays

void applyD1Decay() {
  float decay = d1DecayBase + chokeOffsetMs;
  if (decay < 17.0f) decay = 17.0f;
  d1EffectiveDecay = decay;
  updateD1HoldCache();
  AudioNoInterrupts();
  d1AmpEnv.hold(d1CachedHoldMs);
  d1AmpEnv.decay(d1EffectiveDecay);
  AudioInterrupts();
}

void applyD2Decay() {
  // D2 main decay (choke applied, clamped to 15–1000ms)
  float base2 = d2DecayBase + chokeOffsetMs;
  if (base2 < 15.0f) base2 = 15.0f;
  if (base2 > 1000.0f) base2 = 1000.0f;
  AudioNoInterrupts();
  d2AmpEnv.hold(base2 * 0.5f);
  d2AmpEnv.decay(base2);
  d2Body.length(base2 * 0.25f);
  AudioInterrupts();

  // D2 clap family — use knob position directly for clap curves
  float d2Norm = d2DecayNorm;
  // Flat 93ms below 50%, then accelerating curve → 130ms at 75%, 225ms at 100%
  float clapDecayBase;
  if (d2Norm <= 0.5f) {
    clapDecayBase = 93.0f;
  } else {
    float t = (d2Norm - 0.5f) * 2.0f;  // 0→1 over upper half
    clapDecayBase = 93.0f + 16.0f * t + 116.0f * t * t;
  }
  d2ClapEffectiveDecay = clapDecayBase + chokeOffsetMs;
  if (d2ClapEffectiveDecay < 10.0f) d2ClapEffectiveDecay = 10.0f;

  // Per-burst envelopes: linear 93→111ms over 0–65%, then accelerating to match clap tail
  float burstBase;
  if (d2Norm <= 0.65f) {
    burstBase = 93.0f + d2Norm * 27.0f;       // 93ms at min, ~111ms at 65%
  } else {
    float t = (d2Norm - 0.65f) / 0.35f;       // 0→1 over upper 35%
    burstBase = 111.0f + t * 114.0f;           // 111ms at 65%, 225ms at 100%
  }
  float burstDecay1 = burstBase + chokeOffsetMs * 0.3f;
  float burstDecay2 = (burstBase + 2.0f) + chokeOffsetMs * 0.3f;
  // Clamp burst decay to 80–225ms: floor prevents inaudible tails at full negative choke,
  // ceiling matches the clap master envelope maximum.
  if (burstDecay1 < 80.0f) burstDecay1 = 80.0f;
  if (burstDecay1 > 225.0f) burstDecay1 = 225.0f;
  if (burstDecay2 < 80.0f) burstDecay2 = 80.0f;
  if (burstDecay2 > 225.0f) burstDecay2 = 225.0f;

  AudioNoInterrupts();
  clapAmpEnv1.decay(burstDecay1);
  clapAmpEnv2.decay(burstDecay2);
  clapMasterEnv.decay(d2ClapEffectiveDecay);
  AudioInterrupts();
}

void applyD3Decay() {
  d3EffectiveDecay = computeD3Decay();
  AudioNoInterrupts();
  d3FmAmpEnv.decay(d3EffectiveDecay);
  d3606AmpEnv.decay(d3EffectiveDecay);
  d3Perc.length(d3EffectiveDecay);
  AudioInterrupts();
}

void applyChokeToDecays() {
  applyD1Decay();
  applyD2Decay();
  applyD3Decay();
}

// Animated waveform morph splash screen
void splashAnimation() {
  static constexpr int FRAME_MS    = 28;   // ~36 fps
  static constexpr int TOTAL_FRAMES = 36;
  static constexpr int X_MIN       = 4;
  static constexpr int X_MAX       = 124;
  static constexpr int X_CENTER    = 64;
  static constexpr int Y_CENTER    = 32;
  static constexpr float PI2       = 6.2831853f;

  for (int frame = 0; frame < TOTAL_FRAMES; frame++) {
    unsigned long t0 = millis();
    display.clearDisplay();

    if (frame <= 3) {
      // PHASE 1 — flat line grows from center
      float progress = (float)frame / 3.0f;
      int half = (int)(progress * (X_MAX - X_CENTER));
      int xL = X_CENTER - half;
      int xR = X_CENTER + half;
      if (xL < X_MIN) xL = X_MIN;
      if (xR > X_MAX) xR = X_MAX;
      display.drawLine(xL, Y_CENTER, xR, Y_CENTER, 1);

    } else if (frame <= 12) {
      // PHASE 2 — sine wave emerges
      float progress = (float)(frame - 4) / 8.0f;
      float amplitude = progress * 18.0f;
      float freq = 1.0f + progress * 0.5f;

      int prevY = Y_CENTER;
      for (int x = X_MIN; x <= X_MAX; x++) {
        float t = (float)(x - X_MIN) / (float)(X_MAX - X_MIN);
        float sine = sinf(t * PI2 * freq);
        int y = Y_CENTER - (int)(sine * amplitude);
        if (y < 1) y = 1;
        if (y > 62) y = 62;
        if (x == X_MIN) {
          display.drawPixel(x, y, 1);
        } else {
          display.drawLine(x - 1, prevY, x, y, 1);
        }
        prevY = y;
      }

    } else if (frame <= 28) {
      // PHASE 3 — wavefolding intensifies
      float progress = (float)(frame - 13) / 15.0f;
      float foldAmount = 1.0f + progress * 5.0f;
      float amplitude = 18.0f + progress * 6.0f;
      float freq = 1.5f + progress * 0.5f;
      float drift = sinf(frame * 0.3f) * 0.2f;

      int prevY = Y_CENTER;
      for (int x = X_MIN; x <= X_MAX; x++) {
        float t = (float)(x - X_MIN) / (float)(X_MAX - X_MIN);
        float sine = sinf(t * PI2 * freq + drift);
        // Remap [-1,1] to [0,1]
        float value = (sine + 1.0f) * 0.5f;
        // Wavefold transfer function
        float v = value * foldAmount;
        v = v - floorf(v);
        if ((int)floorf(value * foldAmount) % 2 == 1) v = 1.0f - v;
        float folded = v * 2.0f - 1.0f;

        int y = Y_CENTER - (int)(folded * amplitude);
        if (y < 1) y = 1;
        if (y > 62) y = 62;
        if (x == X_MIN) {
          display.drawPixel(x, y, 1);
        } else {
          display.drawLine(x - 1, prevY, x, y, 1);
        }
        prevY = y;
      }

    } else {
      // PHASE 4 — version info
      display.setTextColor(1);
      display.setTextWrap(false);
      display.setFont(NULL);
      display.setTextSize(1);
      display.setCursor(43, 16);
      display.print("VERSION");
      display.setCursor(55, 28);
      display.print(FIRMWARE_VERSION);
      display.setCursor(10, 40);
      char dateBuf[20];
      snprintf(dateBuf, sizeof(dateBuf), FIRMWARE_DATE_FMT, FIRMWARE_DATE_ARGS);
      display.print(dateBuf);
    }

    display.display();

    // Maintain frame rate
    unsigned long elapsed = millis() - t0;
    if (elapsed < (unsigned long)FRAME_MS) {
      delay(FRAME_MS - elapsed);
    }
  }

  // Hold version text
  delay(800);
  display.clearDisplay();
  display.display();
}

void setup() {
  delay(200);

  // ============================================================================
  // OLED DISPLAY INITIALIZATION
  // ============================================================================

  // Args: (i2cAddr=0 unused for SPI, reset=true to hardware-reset the display)
  bool displayOk = display.begin(0, true);
  if (displayOk) {
    display.clearDisplay();

    // ========================================================================
    // FACTORY RESET — hold MEM button on power-up for 5 seconds
    // ========================================================================

    otherButtonsMux.channel(7);
    delayMicroseconds(10);
    if (!otherButtonsMux.read()) {  // MEM held (active-low)
      display.setTextColor(1);
      display.setTextWrap(false);
      display.setFont(NULL);
      display.setTextSize(2);
      display.setCursor(22, 0);
      display.print("FACTORY");
      display.setCursor(34, 20);
      display.print("RESET");
      display.display();

      bool held = true;
      for (int s = 5; s > 0 && held; s--) {
        display.fillRect(0, 48, 128, 16, 0);
        display.setCursor(58, 48);
        display.print(s);
        display.display();

        for (int i = 0; i < 10 && held; i++) {
          delay(100);
          otherButtonsMux.channel(7);
          delayMicroseconds(10);
          if (otherButtonsMux.read()) held = false;
        }
      }

      if (held) {
        display.clearDisplay();
        display.setCursor(28, 8);
        display.print("EEPROM");
        display.setCursor(22, 28);
        display.print("CLEARED");
        display.display();
        for (int i = 0; i < (int)EEPROM.length(); i++) {
          EEPROM.update(i, 0xFF);
        }
        delay(2000);
      }

      display.clearDisplay();
      display.display();
    }

    // Animated splash screen
    splashAnimation();
  }

  // ============================================================================
  // AUDIO SYSTEM INITIALIZATION
  // ============================================================================

  AudioMemory(1200);  // Delay at 1400ms needs ~483 blocks; 93 audio objects need the rest (RAM2 only, no CPU cost)
  sysTickTimer.begin(sysTickISR, 1000);
  audioInit();
  d1AmpEnv.attack(D1_ATTACK_MS);  // permanent value — not set in audioInit (D1_ATTACK_MS not yet visible there)
  scopeQueue.begin();

  // ============================================================================
  // UI STATE INITIALIZATION
  // ============================================================================

  // Clear overlay and parameter strings at boot (now sysTickMs is valid)
  activeRail = RAIL_NONE;
  displayParameter1[0] = 0;
  displayParameter2[0] = 0;

  noInterrupts();
  parameterOverlayStartTick = sysTickMs - PARAMETER_OVERLAY_DURATION_MS - 1;
  interrupts();

  // Load saved PPQN from EEPROM (defaults to 2 if nothing saved)
  loadPpqnFromEEPROM();

  // ============================================================================
  // HARDWARE INITIALIZATION
  // ============================================================================

  // Initialize shift register and LEDs
  ledShiftReg.setAllLow();
  updateLEDs();

  // Configure ADC hardware averaging — cleaner signal before it reaches software
  analogReadAveraging(KNOB_HW_AVG);

  // Initialize knob smoothing filters
  for (int i = 0; i < knobCount; i++) {
    analog[i] = new ResponsiveAnalogRead(0, true);
    if (!analog[i]) {
      Serial.println("[ERROR] Failed to allocate ResponsiveAnalogRead");
      while (true) { /* halt */ }
    }
    analog[i]->setActivityThreshold(KNOB_ACTIVITY_THRESH);
    analog[i]->setSnapMultiplier(KNOB_SNAP_MULTI);
  }

  // ============================================================================
  // EXTERNAL CLOCK PIN
  // ============================================================================

  pinMode(EXT_CLK_PIN, INPUT_PULLDOWN);
  attachInterrupt(digitalPinToInterrupt(EXT_CLK_PIN), externalClockISR, RISING);

  // Explicitly set GPIO ISR priority to match IntervalTimer default (128).
  // All three ISR sources (externalClockISR on GPIO, stepISR and
  // subdivTimerCallback on PIT) must run at the same NVIC priority so they
  // cannot preempt each other. This makes the non-atomic read-modify-write
  // on pendingStepCount and currentStep safe (see concurrency contract in
  // ext_sync.h). attachInterrupt() does not set priority — it inherits
  // the startup default (128), but we pin it here explicitly so a future
  // Teensy core change can't silently break the assumption.
  NVIC_SET_PRIORITY(IRQ_GPIO6789, 128);

  // ============================================================================
  // LOAD STATE AND START SEQUENCER
  // ============================================================================

  initKnobsFromHardware();
  loadStateFromEEPROM(activeSaveSlot);
  if (loadMonoBassStatusFromEEPROM()) enterMonoBassMode();
  rearmStepTimer();
  applyMasterGain();
}

void loop() {

  // ============================================================================
  // ACCENT PREVIEW TIMEOUT
  // ============================================================================

  // Single stable timebase for top-of-loop checks
  uint32_t loopNowTick;
  noInterrupts();
  loopNowTick = sysTickMs;  // sysTickMs is ISR-written, needs guard
  interrupts();

  // MONOBASS envelope filter decay — runs every 5ms when active
  if (monoBass.active) {
    static uint32_t lastEnvFiltTick = 0;
    if ((uint32_t)(loopNowTick - lastEnvFiltTick) >= 5) {
      lastEnvFiltTick = loopNowTick;
      updateMonoBassEnvFilter(loopNowTick);
    }
  }

  // D1 chroma envelope filter decay — runs every 5ms when d1ChromaMode active.
  // Guard: skip during MONOBASS — MONOBASS owns d1LowPass via its own env filter.
  if (d1ChromaMode && !monoBass.active) {
    static uint32_t lastChromaEnvFiltTick = 0;
    if ((uint32_t)(loopNowTick - lastChromaEnvFiltTick) >= 5) {
      lastChromaEnvFiltTick = loopNowTick;
      updateD1ChromaEnvFilter(loopNowTick);
    }
  }

  // Expire accent preview and restore normal LEDs
  if (accentPreview.active) {
    if ((uint32_t)(loopNowTick - accentPreview.startTick) >= ACCENT_PREVIEW_DURATION_MS) {
      accentPreview.active = false;  // Main-loop only — no guard needed
      updateLEDs();
    }
  }

  // PPQN mode timeout — auto-exit without saving after 5s inactivity
  if (ppqnModeActive) {
    if ((uint32_t)(loopNowTick - ppqnModeLastActivityTick) >= PPQN_MODE_TIMEOUT_MS) {
      ppqnModeActive = false;
      // No save — just exit silently. Normal display resumes automatically.
    }
  }

  // ============================================================================
  // OLED WATCHDOG RECOVERY
  // ============================================================================

  // Atomic check-and-clear prevents losing a flag set between the
  // if-check and the clear (ISR could fire in between otherwise)
  {
    bool needsReinit;
    noInterrupts();
    needsReinit = requestOledReinit;
    requestOledReinit = false;
    interrupts();

    if (needsReinit) {
      display.begin(0, true);  // i2cAddr=0 unused for SPI, reset=true
      display.clearDisplay();
      display.display();

      uint32_t t;
      noInterrupts();
      t = sysTickMs;
      lastFrameDrawTick = t;
      interrupts();
    }
  }

  // ============================================================================
  // EXTERNAL CLOCK: lock-in handoff + timeout detection (ext_sync.h)
  // ============================================================================

  checkExtClockLockIn();
  checkExtClockTimeout();

  // ============================================================================
  // SEQUENCER STEP PROCESSING (before input polling to minimize latency)
  // ============================================================================
  // playSequence() is called at 4 points in loop() (here, post-input,
  // mid-display-draw, and post-OLED) to minimize latency between an ISR
  // queuing a step and the main loop firing audio. Each call is a fast
  // no-op when pendingStepCount == 0.

  if (sequencePlaying) {
    playSequence();
  }
  // Gain is already applied by knob handlers — no per-loop update needed when stopped

  updateExtBpmDisplay();

  // ============================================================================
  // USER INPUT POLLING
  // ============================================================================

  updateOtherButtons();
  updateKnobs();
  updateStepButtons();

  // ============================================================================
  // POST-INPUT STEP PROCESSING
  // ============================================================================
  // Fire any step queued by the PLAY button or ISR immediately,
  // before the OLED draw adds 15-25ms of latency.
  if (sequencePlaying) {
    playSequence();
  }

  // ============================================================================
  // OSCILLOSCOPE DATA ACQUISITION
  // ============================================================================

  updateScopeData();

  // ============================================================================
  // THROTTLED OLED REFRESH (~24 FPS)
  // ============================================================================

  uint32_t tickCopy, lastDrawCopy;

  noInterrupts();
  tickCopy = sysTickMs;
  lastDrawCopy = lastFrameDrawTick;
  interrupts();

  uint32_t frameInterval = (transportState == RUN_EXT)
                           ? OLED_FRAME_INTERVAL_EXT_MS
                           : OLED_FRAME_INTERVAL_MS;
  if ((uint32_t)(tickCopy - lastDrawCopy) >= frameInterval) {
    // Skip OLED frame if a subdivision step is due soon — OLED push takes
    // 15-25ms (SPI bitbang) which would delay the step. Better to drop a
    // display frame than miss a musical beat.
    bool skipForSubdiv = false;
    if (transportState == RUN_EXT && subdivTimerDueUs != 0) {
      uint32_t nowUs = micros();
      int32_t untilDue = (int32_t)(subdivTimerDueUs - nowUs);
      if (untilDue > 0 && (uint32_t)untilDue < OLED_SUBDIV_GUARD_US) {
        skipForSubdiv = true;
      }
    }
    // Skip OLED push when a MONOBASS key event just fired — the SPI transfer
    // would block the CPU for ~1-5ms, adding latency to the next key scan.
    // The skipped frame renders on the next 42ms cycle (imperceptible).
    bool skipForMonoBass = monoBassKeyEvent;
    monoBassKeyEvent = false;
    if (!skipForSubdiv && !skipForMonoBass) {
      updateDisplay();
    }
  }

  // ============================================================================
  // POST-OLED STEP CATCH-UP
  // ============================================================================
  // OLED refresh can block for 15-25ms. Run step processing again so any
  // steps queued during the OLED stall fire promptly instead of waiting
  // for the next full loop iteration. At high tempos this prevents audible lag.
  if (sequencePlaying) {
    playSequence();
  }
}

// Transport state machine — pure state + timer management, no interrupt guards.
//
// transportState is volatile uint8_t (ARM atomic STRB) — the assignment is
// inherently race-safe without explicit masking. This function intentionally
// does NOT call noInterrupts()/interrupts() so it can safely be called from
// within a caller's existing critical section. ARM noInterrupts/interrupts are
// non-nestable: an inner interrupts() call re-enables PRIMASK regardless of
// any outer guard, breaking the caller's atomicity.
//
// Callers that bundle setTransport() with other ISR-shared writes must wrap
// the entire block in noInterrupts()/interrupts():
//   handlePlayStop()    — also writes sequencePlaying, armed, armPulseCountdown
//   enterMonoBassMode() — same (monobass.h)
//   btnMemoryHold()     — also writes sequencePlaying
//
// Callers that change only transportState need no guard (uint8_t is atomic):
//   checkExtClockLockIn(), checkExtClockTimeout()
void setTransport(TransportState s) {
  if (transportState == s) return;

  transportState = s;
  if (s != RUN_EXT) {
    extStepAcc = 0;
    subdivTimer.end();
    subdivStepsRemaining = 0;
    subdivTimerDueUs = 0;
  }

  switch (s) {
    case RUN_INT:
      rearmStepTimer();     // ends + restarts internal clock timer
      break;
    case RUN_EXT:
      stepTimer.end();      // stop internal clock — pulses drive steps now
      // extStepAcc is preserved: the ISR may have already written a valid
      // accumulator value on the locking pulse that triggered this transition.
      break;
    case STOPPED:
    default:
      stepTimer.end();      // stop all timers
      break;
  }
}

// ============================================================================
//  Sequencing and Triggers
// ============================================================================

void playSequence() {
  // Snapshot pendingStepCount and currentStep atomically.
  // ISR advances currentStep and increments pendingStepCount together;
  // reading both inside noInterrupts ensures a consistent snapshot.
  uint8_t toDo;
  uint8_t targetStep;
  noInterrupts();
  toDo = pendingStepCount;
  pendingStepCount = 0;
  targetStep = currentStep;
  interrupts();

  if (toDo == 0) return;

  // With 2 accumulated steps (common at ppqn=2 ext sync, rare on internal
  // clock at high BPM if the main loop stalls briefly), fire both to
  // preserve rhythmic density.  ISR already advanced currentStep twice,
  // so targetStep is the second step; firstStep = targetStep-1.
  // For 3+ steps, skip ahead — a missing step is less noticeable than
  // an off-beat one.
  if (toDo == 2) {
    uint8_t firstStep = (targetStep - 1 + numSteps) % numSteps;
    playSequenceCore(firstStep);   // fire first step
    playSequenceCore(targetStep);  // fire second step
  } else {
    // Single step or skip-ahead — fire only the latest step.
    // ISR already advanced currentStep past any skipped steps.
    playSequenceCore(targetStep);
  }

  updateLEDs();
}

// Trigger active drums for a specific step.
// Step advancement happens in ISR (stepISR / externalClockISR / subdivTimerCallback),
// so this function only fires audio — no step counter mutation.
// Called from main loop context via playSequence().
void playSequenceCore(uint8_t step) {
  // MONOBASS mode: entire sequencer suppressed — D1 is live keyboard only
  if (monoBass.active) return;

  if (d1Sequence[step]) {
    if (d1ChromaMode) {
      d1BaseFreq = d1ChromaFreq(d1ChromaNote[step]);
      applyD1Freq();
    }
    triggerD1();
  }
  if (d2Sequence[step]) {
    if (d2ChromaMode) {
      applyD2ChromaFreq(d2ChromaNote[step]);
    }
    triggerD2();
  }
  if (d3Sequence[step]) {
    if (d3ChromaMode) {
      applyD3ChromaFreq(d3ChromaNote[step]);
    }
    triggerD3(step);
  }
}

// Decay d1LowPass from its trigger peak back toward d1ChromaEnvFiltBaseHz.
// Mirrors updateMonoBassEnvFilter() but uses D1 decay time as the tau source.
// Call from loop() every ~5ms when d1ChromaMode is active.
void updateD1ChromaEnvFilter(uint32_t nowMs) {
  if (!d1ChromaMode) return;
  if (d1ChromaEnvFiltDepth < 0.01f) return;

  if (d1ChromaEnvFiltTrigger == 0) {
    // No trigger yet — hold at resting cutoff so body-knob moves are heard.
    AudioNoInterrupts();
    d1LowPass.frequency(d1ChromaEnvFiltBaseHz);
    d1LowPass.resonance(1.5f);
    AudioInterrupts();
    return;
  }

  uint32_t elapsed = nowMs - d1ChromaEnvFiltTrigger;
  float tauMs = d1EffectiveDecay * 0.6f + 40.0f;
  float decay = expf(-(float)elapsed / tauMs);

  static constexpr float kEnvFiltCeiling = 5000.0f;
  float peak = d1ChromaEnvFiltBaseHz
             + d1ChromaEnvFiltDepth * (kEnvFiltCeiling - d1ChromaEnvFiltBaseHz);
  if (peak > kEnvFiltCeiling) peak = kEnvFiltCeiling;
  float cutoff = d1ChromaEnvFiltBaseHz + (peak - d1ChromaEnvFiltBaseHz) * decay;
  if (cutoff < 20.0f) cutoff = 20.0f;

  float resonance = 1.5f + 2.0f * d1ChromaEnvFiltDepth * decay;

  AudioNoInterrupts();
  d1LowPass.frequency(cutoff);
  d1LowPass.resonance(resonance);
  AudioInterrupts();
}

void triggerD1() {
  // Retrigger guard — uint32_t reads/writes are atomic on ARM Cortex-M7.
  // Called from main loop context via playSequenceCore().
  uint32_t now = micros();
  bool skipNoteOff = !monoBass.active && (now - lastD1TriggerUs) < MIN_RETRIGGER_US;
  lastD1TriggerUs = now;

  AudioNoInterrupts();
  if (monoBass.active) {
    // Gate-style: retrigger amp envelope + snap, no pitch sweep
    d1AmpEnv.noteOff();
    d1AmpEnv.noteOn();
    d1Snap.noteOn();
  } else {
    d1AmpEnv.hold(d1CachedHoldMs);
    d1AmpEnv.decay(d1EffectiveDecay);
    if (!skipNoteOff) {
      d1AmpEnv.noteOff();
      d1PitchEnv.noteOff();
    }
    d1AmpEnv.noteOn();
    d1PitchEnv.noteOn();
    d1Snap.noteOn();
    if (d1ChromaMode && d1ChromaEnvFiltDepth > 0.01f) {
      d1ChromaEnvFiltTrigger = sysTickMs;
      float peak = d1ChromaEnvFiltBaseHz
                 + d1ChromaEnvFiltDepth * (5000.0f - d1ChromaEnvFiltBaseHz);
      if (peak > 5000.0f) peak = 5000.0f;
      d1LowPass.frequency(peak);
      d1LowPass.resonance(1.5f + 2.0f * d1ChromaEnvFiltDepth);
    }
  }
  AudioInterrupts();
}

// Trigger D2 (snare/clap) — called from main loop via playSequenceCore().
// Handles retrigger guard and envelope noteOff/noteOn.
// Decay values are already set by applyChokeToDecays() when choke or decay knob changes.
void triggerD2() {
  uint32_t now = micros();
  bool skipNoteOff = (now - lastD2TriggerUs) < MIN_RETRIGGER_US;
  lastD2TriggerUs = now;

  AudioNoInterrupts();
  if (!skipNoteOff) {
    d2AmpEnv.noteOff();
    clapAmpEnv1.noteOff();
    clapAmpEnv2.noteOff();
    clapMasterEnv.noteOff();
    d2NoiseEnv.noteOff();
  }
  d2AmpEnv.noteOn();
  clapAmpEnv1.noteOn();
  clapAmpEnv2.noteOn();
  clapMasterEnv.noteOn();
  d2Body.noteOn();
  d2ClickTransient.noteOn();
  d2NoiseEnv.noteOn();
  AudioInterrupts();
}

// Trigger D3 (hi-hat) — called from main loop via playSequenceCore().
// Applies accent pattern if active, handles retrigger guard.
void triggerD3(uint8_t step) {
  uint32_t now = micros();
  bool skipNoteOff = (now - lastD3TriggerUs) < MIN_RETRIGGER_US;
  lastD3TriggerUs = now;

  // Use cached decay and accent mask (updated by applyChokeToDecays / accent knob)
  float applyDecay = d3EffectiveDecay;

  // step is always 0–15 (uint8_t from currentStep % numSteps)
  if (d3AccentMask && ((d3AccentMask >> ((numSteps - 1) - step)) & 1)) {
    applyDecay *= D3_ACCENT_FACTOR;
  }

  AudioNoInterrupts();
  d3FmAmpEnv.decay(applyDecay);
  d3606AmpEnv.decay(applyDecay);
  d3Perc.length(applyDecay);
  if (!skipNoteOff) {
    d3FmAmpEnv.noteOff();
    d3606AmpEnv.noteOff();
  }
  d3FmAmpEnv.noteOn();
  d3606AmpEnv.noteOn();
  d3Perc.noteOn();
  AudioInterrupts();
}

// ============================================================================
//  Buttons and LEDs
// ============================================================================

// PLAY/STOP handler — called on button 6 press from updateOtherButtons().
void handlePlayStop() {
  if (!sequencePlaying) {
    // Check for recent external sync pulses — even 1 is enough for drop-in.
    // Lock-in auto-detect requires 3 pulses (two similar intervals),
    // which is too strict for explicit drop-in. Here we only need to know
    // "has the Volca been sending clock recently?"
    bool hasRecentPulse = false;
    noInterrupts();
    uint32_t lastP = lastPulseMicros;
    interrupts();
    if (lastP != 0 && (micros() - lastP) < EXT_TIMEOUT_US) {
      hasRecentPulse = true;
    }

    // PLAY = ARM. No step fires here. The next external pulse (or
    // internal tick for RUN_INT) fires step 0.
    subdivTimer.end();
    // Snapshot sysTickMs before the critical section — avoids reading
    // the volatile inside noInterrupts() where it can't update anyway.
    uint32_t nowTick = sysTickMs;
    // Wide critical section — all ISR-shared state must be initialized
    // before setTransport() arms the timer that creates the ISR source.
    noInterrupts();
    pendingStepCount = 0;
    extStepAcc = 0;
    subdivStepsRemaining = 0;
    subdivTimerDueUs = 0;

    if (hasRecentPulse) {
      // External sync — count-in for one full cycle, then fire step 0.
      armed = true;
      armPulseCountdown = (uint32_t)numSteps * ppqn / STEPS_PER_BEAT;

      // Grace window: snap to nearest pulse.
      // If the user pressed PLAY just after a pulse (within the first
      // half of a pulse interval), credit that pulse to the count-in.
      // Guard: keep at least 1 so the ISR fires step 0 on a real pulse.
      uint32_t ema = extIntervalEMA;       // safe: interrupts already off
      uint32_t elapsed = micros() - lastPulseMicros;
      if (ema > 0 && elapsed < (ema / 2) && armPulseCountdown > 1) {
        armPulseCountdown--;
      }

      sequencePlaying = true;
      setTransport(RUN_EXT);
    } else {
      // No external clock — start on internal timer immediately.
      // currentStep = numSteps-1 so the first internal tick advances to step 0.
      armed = false;
      armPulseCountdown = 0;
      currentStep = numSteps - 1;
      sequencePlaying = true;
      setTransport(RUN_INT);
    }
    displayBlockedUntilTick = nowTick + 500;  // suppress OLED push during drop-in
    interrupts();
  } else {
    // STOP — also aborts armed count-in if active.
    // Preserves pulse timing state so ext clock is detected
    // immediately on the next PLAY press.
    noInterrupts();
    sequencePlaying = false;
    setTransport(STOPPED);
    armed = false;
    armPulseCountdown = 0;
    pendingStepCount = 0;
    wantSwitchToExt = false;
    interrupts();
    applyMasterGain();
  }
}

// Button index → function mapping:
//   0 = D1 SEQ SELECT   (short press: selectTrack, long hold: toggle D1 chroma mode)
// ============================================================================
//  Button handler state machine
// ============================================================================

struct ButtonHandler {
  uint32_t pressTick = 0;
  bool enteredMode = false;   // first-tier hold (chroma / PPQN)
  bool enteredMode2 = false;  // second-tier hold (D1 MONOBASS only)

  void (*onPress)(ButtonHandler& self, uint32_t nowTick);
  void (*onRelease)(ButtonHandler& self, uint32_t nowTick);
  void (*onHoldCheck)(ButtonHandler& self, uint32_t nowTick, uint32_t heldMs);
};

// --- D1 button (index 0): short=selectD1, hold 1.5s=chroma, hold 6s=MONOBASS ---

static void btnD1Press(ButtonHandler& self, uint32_t nowTick) {
  self.pressTick = nowTick;
  self.enteredMode = false;   // chroma
  self.enteredMode2 = false;  // MONOBASS
}

static void btnD1Release(ButtonHandler& self, uint32_t /*nowTick*/) {
  if (!self.enteredMode && !self.enteredMode2 && !monoBass.active) {
    selectTrack(TRACK_D1);
  }
  self.enteredMode = false;
  self.enteredMode2 = false;
}

static void btnD1Hold(ButtonHandler& self, uint32_t nowTick, uint32_t heldMs) {
  // Tier 1: CHROMA at 1.5s
  if (!self.enteredMode && !self.enteredMode2 && heldMs >= D1_CHROMA_LONG_PRESS_MS) {
    d1ChromaMode = !d1ChromaMode;
    self.enteredMode = true;
    if (d1ChromaMode) {
      d1FreqBeforeChroma = d1BaseFreq;
      selectTrack(TRACK_D1);
      // Lower HPF to pass bass fundamentals (C2 = 65 Hz, normal HPF at 85 Hz kills it)
      AudioNoInterrupts();
      d1HighPass.frequency(30.0f);
      d1HighPass.resonance(0.7f);
      AudioInterrupts();
      applyKnobToEngine(6, analog[6]->getValue());  // switch Body to filter mode (sets d1ChromaEnvFiltBaseHz)
      d1ChromaEnvFiltDepth = normalizeKnob(analog[5]->getValue());
      d1ChromaEnvFiltTrigger = 0;
    } else {
      d1ChromaHeldStep = -1;
      d1ChromaEnvFiltTrigger = 0;
      d1BaseFreq = d1FreqBeforeChroma;
      applyD1Freq();
      // Restore drum HPF, Body EQ, and d1LowPass to drum defaults.
      // Skip HPF override during MONOBASS (which holds it at 30 Hz).
      if (!monoBass.active) {
        AudioNoInterrupts();
        d1HighPass.frequency(85.0f);
        d1HighPass.resonance(2.0f);
        d1LowPass.frequency(1800.0f);
        d1LowPass.resonance(1.5f);
        AudioInterrupts();
      }
      applyKnobToEngine(6, analog[6]->getValue());  // restore normal EQ
    }
    snprintf(displayParameter1, sizeof(displayParameter1),
             d1ChromaMode ? "D1 CHROMA ON" : "D1 CHROMA OFF");
    displayParameter2[0] = '\0';
    parameterOverlayStartTick = nowTick;
  }
  // Tier 2: MONOBASS at 6s
  if (!self.enteredMode2 && heldMs >= D1_MONOBASS_LONG_PRESS_MS) {
    self.enteredMode2 = true;
    if (!monoBass.active) {
      enterMonoBassMode();
    } else {
      exitMonoBassMode();
    }
    snprintf(displayParameter1, sizeof(displayParameter1),
             monoBass.active ? "MONOBASS ON" : "MONOBASS OFF");
    displayParameter2[0] = '\0';
    parameterOverlayStartTick = nowTick;
    updateLEDs();
  }
}

// --- D2 button (index 1): short=selectD2, hold 2s=chroma ---

static void btnD2Press(ButtonHandler& self, uint32_t nowTick) {
  if (monoBass.active) return;
  self.pressTick = nowTick;
  self.enteredMode = false;
}

static void btnD2Release(ButtonHandler& self, uint32_t /*nowTick*/) {
  if (monoBass.active) return;
  if (!self.enteredMode) selectTrack(TRACK_D2);
  self.enteredMode = false;
}

static void btnD2Hold(ButtonHandler& self, uint32_t nowTick, uint32_t heldMs) {
  if (monoBass.active || self.enteredMode) return;
  if (heldMs >= D2_CHROMA_LONG_PRESS_MS) {
    d2ChromaMode = !d2ChromaMode;
    self.enteredMode = true;
    if (d2ChromaMode) {
      selectTrack(TRACK_D2);
    } else {
      d2ChromaHeldStep = -1;
    }
    applyKnobToEngine(8, analog[8]->getValue());
    snprintf(displayParameter1, sizeof(displayParameter1),
             d2ChromaMode ? "D2 CHROMA ON" : "D2 CHROMA OFF");
    displayParameter2[0] = '\0';
    parameterOverlayStartTick = nowTick;
  }
}

// --- D3 button (index 2): short=selectD3, hold 2s=chroma ---

static void btnD3Press(ButtonHandler& self, uint32_t nowTick) {
  if (monoBass.active) return;
  self.pressTick = nowTick;
  self.enteredMode = false;
}

static void btnD3Release(ButtonHandler& self, uint32_t /*nowTick*/) {
  if (monoBass.active) return;
  if (!self.enteredMode) selectTrack(TRACK_D3);
  self.enteredMode = false;
}

static void btnD3Hold(ButtonHandler& self, uint32_t nowTick, uint32_t heldMs) {
  if (monoBass.active || self.enteredMode) return;
  if (heldMs >= D3_CHROMA_LONG_PRESS_MS) {
    d3ChromaMode = !d3ChromaMode;
    self.enteredMode = true;
    if (d3ChromaMode) {
      selectTrack(TRACK_D3);
    } else {
      d3ChromaHeldStep = -1;
    }
    applyKnobToEngine(16, analog[16]->getValue());
    snprintf(displayParameter1, sizeof(displayParameter1),
             d3ChromaMode ? "D3 CHROMA ON" : "D3 CHROMA OFF");
    displayParameter2[0] = '\0';
    parameterOverlayStartTick = nowTick;
  }
}

// --- PLAY button (index 6): short=play/stop, hold 2s=WF chroma ---

static void btnPlayPress(ButtonHandler& self, uint32_t nowTick) {
  self.pressTick = nowTick;
  self.enteredMode = false;
}

static void btnPlayRelease(ButtonHandler& self, uint32_t /*nowTick*/) {
  if (!self.enteredMode && !monoBass.active) handlePlayStop();
  self.enteredMode = false;
}

static void btnPlayHold(ButtonHandler& self, uint32_t nowTick, uint32_t heldMs) {
  if (self.enteredMode) return;
  if (heldMs >= WF_CHROMA_LONG_PRESS_MS) {
    if (monoBass.active) {
      // WF chroma is force-enabled during MONOBASS — block toggle to avoid
      // user changes being silently overwritten on exit (savedWfChroma restore).
      self.enteredMode = true;
      snprintf(monoBass.paramLabel, sizeof(monoBass.paramLabel), "WF CHROMA");
      snprintf(monoBass.paramValue, sizeof(monoBass.paramValue), "LOCKED");
      monoBass.paramShowStart = sysTickMs;
      return;
    }
    wfChromaMode = !wfChromaMode;
    self.enteredMode = true;
    {
      snprintf(displayParameter1, sizeof(displayParameter1),
               wfChromaMode ? "WF CHROMA ON" : "WF CHROMA OFF");
      displayParameter2[0] = '\0';
      parameterOverlayStartTick = nowTick;
    }
  }
}

// --- MEMORY button (index 7): short=cycle slot, hold 2s=PPQN mode ---

static void btnMemoryPress(ButtonHandler& self, uint32_t nowTick) {
  if (monoBass.active) {
    snprintf(displayParameter1, sizeof(displayParameter1), "DISABLED FOR");
    snprintf(displayParameter2, sizeof(displayParameter2), "MONOBASS");
    parameterOverlayStartTick = nowTick;
    activeRail = RAIL_NONE;
    return;
  }
  self.pressTick = nowTick;
  self.enteredMode = false;
}

static void btnMemoryRelease(ButtonHandler& self, uint32_t nowTick) {
  if (monoBass.active) return;
  if (self.enteredMode) {
    // Hold entered PPQN mode — suppress slot cycle
  } else if (ppqnModeActive) {
    // Short press in PPQN mode — cycle to next value
    uint8_t idx = 0;
    for (int j = 0; j < PPQN_OPTION_COUNT; j++) {
      if (PPQN_OPTIONS[j] == ppqnModeSelection) { idx = j; break; }
    }
    ppqnModeSelection = PPQN_OPTIONS[(idx + 1) % PPQN_OPTION_COUNT];
    ppqnModeLastActivityTick = nowTick;
  } else {
    // Short press — cycle memory slot
    activeSaveSlot = (activeSaveSlot + 1) % SAVE_SLOT_COUNT;
    snprintf(displayParameter1, sizeof(displayParameter1), "SLOT %d", activeSaveSlot + 1);
    snprintf(displayParameter2, sizeof(displayParameter2), "SELECT");
    parameterOverlayStartTick = nowTick;
  }
  self.enteredMode = false;
}

static void btnMemoryHold(ButtonHandler& self, uint32_t nowTick, uint32_t heldMs) {
  if (monoBass.active) return;
  if (self.enteredMode) return;
  if (heldMs < PPQN_LONG_PRESS_MS) return;

  if (ppqnModeActive) {
    ppqn = ppqnModeSelection;
    savePpqnToEEPROM(ppqn);
    ppqnModeActive = false;
    snprintf(displayParameter1, sizeof(displayParameter1), "PPQN %d", ppqn);
    snprintf(displayParameter2, sizeof(displayParameter2), "SAVED");
    parameterOverlayStartTick = nowTick;
    activeRail = RAIL_NONE;
  } else {
    if (sequencePlaying) {
      noInterrupts();
      sequencePlaying = false;
      setTransport(STOPPED);
      interrupts();
      resetExternalClockState();
      applyMasterGain();
    }
    ppqnModeActive = true;
    ppqnModeLastActivityTick = nowTick;
    ppqnModeSelection = ppqn;
  }
  self.enteredMode = true;
}

// --- LOAD button (index 8): press-only ---

static void btnLoadPress(ButtonHandler& self, uint32_t nowTick) {
  (void)self;
  if (monoBass.active) {
    snprintf(displayParameter1, sizeof(displayParameter1), "DISABLED FOR");
    snprintf(displayParameter2, sizeof(displayParameter2), "MONOBASS");
    parameterOverlayStartTick = nowTick;
    activeRail = RAIL_NONE;
    return;
  }
  if (!loadStateFromEEPROM(activeSaveSlot)) {
    for (int step = 0; step < numSteps; step++) {
      d1Sequence[step] = 0;
      d2Sequence[step] = 0;
      d3Sequence[step] = 0;
      d1ChromaNote[step] = 36;
      d2ChromaNote[step] = 48;
      d3ChromaNote[step] = 48;
    }
    updateLEDs();
    patternDirty = false;
    activeRail = RAIL_NONE;
    snprintf(displayParameter1, sizeof(displayParameter1), "SLOT %d", activeSaveSlot + 1);
    snprintf(displayParameter2, sizeof(displayParameter2), "EMPTY");
    parameterOverlayStartTick = nowTick;
  }
}

// --- SAVE button (index 9): press-only ---

static void btnSavePress(ButtonHandler& self, uint32_t nowTick) {
  (void)self;
  if (monoBass.active) {
    snprintf(displayParameter1, sizeof(displayParameter1), "DISABLED FOR");
    snprintf(displayParameter2, sizeof(displayParameter2), "MONOBASS");
    parameterOverlayStartTick = nowTick;
    activeRail = RAIL_NONE;
    return;
  }
  activeRail = RAIL_NONE;
  if (patternDirty) {
    saveStateToEEPROM(activeSaveSlot);
  } else {
    snprintf(displayParameter1, sizeof(displayParameter1), "PATTERN");
    snprintf(displayParameter2, sizeof(displayParameter2), "CLEAN");
    parameterOverlayStartTick = nowTick;
  }
}

// --- Null handler for unassigned buttons (3, 4, 5) ---
static void btnNullPress(ButtonHandler& s, uint32_t t) { (void)s; (void)t; }
static void btnNullRelease(ButtonHandler& s, uint32_t t) { (void)s; (void)t; }
static void btnNullHold(ButtonHandler& s, uint32_t t, uint32_t h) { (void)s; (void)t; (void)h; }

// --- Handler table (indices 0–9 match otherButtonsMux channels) ---
static ButtonHandler btnHandlers[otherButtonsCount] = {
  /* 0 D1     */ { 0, false, false, btnD1Press,     btnD1Release,     btnD1Hold     },
  /* 1 D2     */ { 0, false, false, btnD2Press,     btnD2Release,     btnD2Hold     },
  /* 2 D3     */ { 0, false, false, btnD3Press,     btnD3Release,     btnD3Hold     },
  /* 3 n/a    */ { 0, false, false, btnNullPress,   btnNullRelease,   btnNullHold   },
  /* 4 n/a    */ { 0, false, false, btnNullPress,   btnNullRelease,   btnNullHold   },
  /* 5 n/a    */ { 0, false, false, btnNullPress,   btnNullRelease,   btnNullHold   },
  /* 6 PLAY   */ { 0, false, false, btnPlayPress,   btnPlayRelease,   btnPlayHold   },
  /* 7 MEMORY */ { 0, false, false, btnMemoryPress, btnMemoryRelease, btnMemoryHold },
  /* 8 LOAD   */ { 0, false, false, btnLoadPress,   btnNullRelease,   btnNullHold   },
  /* 9 SAVE   */ { 0, false, false, btnSavePress,   btnNullRelease,   btnNullHold   },
};

// ============================================================================
//  Generic button scan loop — debounce + dispatch
// ============================================================================

void updateOtherButtons() {
  static uint32_t lastDebounceTick[otherButtonsCount] = { 0 };
  static bool btnState[otherButtonsCount] = { false };
  static bool btnLastState[otherButtonsCount] = { false };

  uint32_t nowTick;
  noInterrupts();
  nowTick = sysTickMs;
  interrupts();

  for (int i = 0; i < otherButtonsCount; i++) {
    otherButtonsMux.channel(i);
    delayMicroseconds(5);
    bool rawPressed = !otherButtonsMux.read();

    if (rawPressed != btnLastState[i]) {
      lastDebounceTick[i] = nowTick;
    }

    uint16_t debounceMs = (i == 6) ? PLAY_DEBOUNCE_MS : BUTTON_DEBOUNCE_MS;
    if ((uint32_t)(nowTick - lastDebounceTick[i]) > debounceMs && (rawPressed != btnState[i])) {
      btnState[i] = rawPressed;
      if (btnState[i]) {
        btnHandlers[i].onPress(btnHandlers[i], nowTick);
      } else {
        btnHandlers[i].onRelease(btnHandlers[i], nowTick);
      }
    }

    // Continuous hold check — runs every scan iteration while button is held
    if (btnState[i]) {
      uint32_t heldMs = (uint32_t)(nowTick - btnHandlers[i].pressTick);
      btnHandlers[i].onHoldCheck(btnHandlers[i], nowTick, heldMs);
    }

    btnLastState[i] = rawPressed;
  }
}

void selectTrack(Track t) {
  activeTrack = t;
  updateLEDs();
}

void updateLEDs() {
  // Main-loop only — no ISR access to accentPreview*, no guards needed

  // MONOBASS mode — first 12 LEDs lit as usable-key indicators (12 notes/octave)
  if (monoBass.active) {
    for (int i = 0; i < numSteps; i++) {
      ledShiftReg.setNoUpdate(i, i < 12);
    }
    ledShiftReg.updateRegisters();
    return;
  }

  bool preview = accentPreview.active;
  uint16_t mask = accentPreview.mask;

  // Accent preview mode (temporary display)
  if (preview) {
    for (int i = 0; i < numSteps; i++) {
      bool on = (mask >> ((numSteps - 1) - i)) & 1;
      ledShiftReg.setNoUpdate(i, on);
    }
    ledShiftReg.updateRegisters();
    return;
  }

  // Normal pattern display with optional current step indicator
  uint8_t* seq = sequenceForTrack(activeTrack);

  // Snapshot play state — both volatile (ISR-written)
  uint8_t currentStepSnap;
  bool playingSnap;
  noInterrupts();
  currentStepSnap = currentStep;
  playingSnap = sequencePlaying;
  interrupts();

  for (int i = 0; i < numSteps; i++) {
    bool ledState = seq[i];

    // Force current step ON when playing (creates moving bright spot)
    if (playingSnap && i == currentStepSnap) {
      ledState = true;
    }

    ledShiftReg.setNoUpdate(i, ledState);
  }
  ledShiftReg.updateRegisters();
}

// Returns the active chroma held-step pointer for the current track, or nullptr
static inline int8_t* activeChromaHeldStep() {
  if (d1ChromaMode && activeTrack == TRACK_D1) return &d1ChromaHeldStep;
  if (d2ChromaMode && activeTrack == TRACK_D2) return &d2ChromaHeldStep;
  if (d3ChromaMode && activeTrack == TRACK_D3) return &d3ChromaHeldStep;
  return nullptr;
}

// Returns the per-step MIDI note array for the active chroma channel, or nullptr
static inline uint8_t* activeChromaNotes() {
  if (d1ChromaMode && activeTrack == TRACK_D1) return d1ChromaNote;
  if (d2ChromaMode && activeTrack == TRACK_D2) return d2ChromaNote;
  if (d3ChromaMode && activeTrack == TRACK_D3) return d3ChromaNote;
  return nullptr;
}

void updateStepButtons() {
  static uint32_t lastDebounceTick[stepButtonCount] = { 0 };
  static bool btnState[stepButtonCount] = { false };
  static bool btnLastState[stepButtonCount] = { false };
  static uint32_t stepPressTick[stepButtonCount] = { 0 };

  uint8_t* seq = sequenceForTrack(activeTrack);

  // single stable timebase for this whole scan
  uint32_t nowTick;
  noInterrupts();
  nowTick = sysTickMs;
  interrupts();

  for (int i = 0; i < stepButtonCount; i++) {
    stepButtonsMux.channel(i);
    delayMicroseconds(5);
    bool rawPressed = !stepButtonsMux.read();  // no arg — use channel already set above

    if (rawPressed != btnLastState[i]) {
      lastDebounceTick[i] = nowTick;
    }

    uint16_t debounceMs = monoBass.active ? MONOBASS_DEBOUNCE_MS : STEP_DEBOUNCE_MS;
    if ((uint32_t)(nowTick - lastDebounceTick[i]) > debounceMs && (rawPressed != btnState[i])) {

      btnState[i] = rawPressed;

      // MONOBASS mode — buttons trigger D1 directly, skip all sequence editing
      if (handleMonoBassButton(i, btnState[i])) {
        btnLastState[i] = rawPressed;
        continue;
      }

      int8_t* heldStep = activeChromaHeldStep();

      if (btnState[i]) {
        // Press down
        if (heldStep) {
          // Chroma mode — defer toggle to release (to distinguish from hold)
          stepPressTick[i] = nowTick;
        } else {
          // Normal mode — toggle step immediately
          seq[i] ^= 1;
          ledShiftReg.set(i, seq[i]);
          patternDirty = true;
        }
      } else {
        // Release
        if (heldStep) {
          if (*heldStep == i) {
            // Was in note-select — just clear, no toggle
            *heldStep = -1;
          } else {
            // Short press — toggle step
            seq[i] ^= 1;
            ledShiftReg.set(i, seq[i]);
            patternDirty = true;
          }
        }
      }
    }

    // Chroma note-select: after holding a step button for 300ms, enter note-select
    if (!monoBass.active) {
      int8_t* heldStep = activeChromaHeldStep();
      if (heldStep && btnState[i]) {
        if (*heldStep == i) {
          // Already in note-select — keep overlay alive
          uint8_t* notes = activeChromaNotes();
          char noteName[8];
          formatChromaNote(notes[i], noteName);
          snprintf(displayParameter1, sizeof(displayParameter1), "STEP %d", i + 1);
          snprintf(displayParameter2, sizeof(displayParameter2), "%s", noteName);
          parameterOverlayStartTick = nowTick;
        } else if ((uint32_t)(nowTick - stepPressTick[i]) >= CHROMA_STEP_HOLD_MS) {
          *heldStep = i;
        }
      }
    }

    btnLastState[i] = rawPressed;
  }
}

int readKnobRaw(uint8_t idx) {
  admux::Mux& mux = (idx < 16) ? knobMux1 : knobMux2;
  mux.channel(idx < 16 ? idx : idx - 16);
  delayMicroseconds(KNOB_MUX_SETTLE_US);
  int sum = 0;
  for (int i = 0; i < KNOB_OVERSAMPLE; i++) {
    sum += mux.read();
  }
  int raw = sum / KNOB_OVERSAMPLE;
  // Clamp ADC edges: pots rarely hit true 0/1023 — map the reliable
  // range to the full 0-1023 so both extremes are always reachable.
  raw = constrain(raw, 3, 1020);
  return map(raw, 3, 1020, 0, 1023);
}

// ============================================================================
//  Shared curve helpers — used by both display and engine switch blocks
//  to keep the mapping in one place.
// ============================================================================

// D1 Decay curve: piecewise 50–70 ms (low range) then 70–1000 ms (high range)
static inline float d1DecayCurve(int knobValue) {
  float norm = normalizeKnob(knobValue);
  if (norm <= 0.25f) {
    float blend = norm / 0.25f;
    return 50.0f + (70.0f - 50.0f) * blend;
  } else {
    float blend = (norm - 0.25f) / 0.75f;
    return 70.0f + (1000.0f - 70.0f) * blend;
  }
}

// D1 Pitch curve: piecewise 55–110 Hz (A1→A2) then 110–440 Hz (A2→A4)
static inline float d1PitchCurve(int knobValue) {
  float norm = normalizeKnob(knobValue);
  if (norm <= 0.33f) {
    float blend = norm / 0.33f;
    return 55.0f + (110.0f - 55.0f) * blend;   // A1(55) → A2(110)
  } else {
    float blend = (norm - 0.33f) / 0.67f;
    return 110.0f + (440.0f - 110.0f) * blend;  // A2(110) → A4(440)
  }
}

// D1 chroma note range (MIDI 33=A1 through 75=D#5)
static constexpr uint8_t D1_CHROMA_NOTE_MIN = 33;
static constexpr uint8_t D1_CHROMA_NOTE_MAX = 75;

// Shared MIDI-to-Hz lookup table covering MIDI 33 (A1) through 84 (C6).
// Used by D1/D2/D3 chroma modes and wavefolder chroma — replaces per-voice
// expf()/powf() calls with a single 208-byte flash table.
static constexpr uint8_t MIDI_FREQ_MIN = 33;
static constexpr uint8_t MIDI_FREQ_MAX = 84;

static const float MIDI_FREQ[] = {
  // MIDI 33   34       35       36       37       38       39       40
  55.000f, 58.270f, 61.735f, 65.406f, 69.296f, 73.416f, 77.782f, 82.407f,
  // MIDI 41   42       43       44       45       46       47       48
  87.307f, 92.499f, 97.999f, 103.826f, 110.000f, 116.541f, 123.471f, 130.813f,
  // MIDI 49   50       51       52       53       54       55       56
  138.591f, 146.832f, 155.563f, 164.814f, 174.614f, 184.997f, 195.998f, 207.652f,
  // MIDI 57   58       59       60       61       62       63       64
  220.000f, 233.082f, 246.942f, 261.626f, 277.183f, 293.665f, 311.127f, 329.628f,
  // MIDI 65   66       67       68       69       70       71       72
  349.228f, 369.994f, 391.995f, 415.305f, 440.000f, 466.164f, 493.883f, 523.251f,
  // MIDI 73   74       75       76       77       78       79       80
  554.365f, 587.330f, 622.254f, 659.255f, 698.456f, 739.989f, 783.991f, 830.609f,
  // MIDI 81   82       83       84
  880.000f, 932.328f, 987.767f, 1046.502f
};

static_assert(sizeof(MIDI_FREQ) / sizeof(MIDI_FREQ[0]) == (MIDI_FREQ_MAX - MIDI_FREQ_MIN + 1),
              "MIDI_FREQ must have one entry per MIDI note in range");

// Clamp-and-lookup: safe for any uint8_t input.
float midiToFreq(uint8_t midiNote) {
  uint8_t idx = constrain(midiNote, MIDI_FREQ_MIN, MIDI_FREQ_MAX) - MIDI_FREQ_MIN;
  return MIDI_FREQ[idx];
}

float d1ChromaFreq(uint8_t midiNote) {
  return midiToFreq(midiNote);
}

// Chroma pitch: writes note name string for display.
// outName must be >= 5 chars.
static inline void formatChromaNote(uint8_t midiNote, char* outName) {
  static const char* NOTE_NAMES[] = {
    "C","C#","D","D#","E","F","F#","G","G#","A","A#","B"
  };
  snprintf(outName, 5, "%s%d", NOTE_NAMES[midiNote % 12], (midiNote / 12) - 1);
}

// Maps knob 0–1023 to MIDI note in A1(33)–D#5(75) range, quantized.
static inline uint8_t d1ChromaKnobToNote(int knobValue) {
  float semi = (knobValue / 1023.0f) * (float)(D1_CHROMA_NOTE_MAX - D1_CHROMA_NOTE_MIN);
  int note = constrain((int)(semi + 0.5f), 0, D1_CHROMA_NOTE_MAX - D1_CHROMA_NOTE_MIN);
  return (uint8_t)(note + D1_CHROMA_NOTE_MIN);
}

// D2 chroma mode constants
static constexpr uint8_t D2_CHROMA_NOTE_MIN = 45;  // A2
static constexpr uint8_t D2_CHROMA_NOTE_MAX = 69;  // A4

// Maps knob 0–1023 linearly to MIDI note in A2(45)–A4(69) range, quantized.
static inline uint8_t d2ChromaKnobToNote(int knobValue) {
  float semi = (knobValue / 1023.0f) * (float)(D2_CHROMA_NOTE_MAX - D2_CHROMA_NOTE_MIN);
  return (uint8_t)constrain((int)(semi + 0.5f) + D2_CHROMA_NOTE_MIN,
                             D2_CHROMA_NOTE_MIN, D2_CHROMA_NOTE_MAX);
}

// Sets d2Osc frequency from MIDI note. Called per-step during playback
// when D2 chroma mode is active. Only d2Osc is pitched — d2Body stays fixed.
void applyD2ChromaFreq(uint8_t midiNote) {
  AudioNoInterrupts();
  d2Osc.frequency(midiToFreq(midiNote));
  AudioInterrupts();
}

// D3 chroma mode constants
static constexpr uint8_t D3_HARM_NOTE_MIN = 48;  // C3
static constexpr uint8_t D3_HARM_NOTE_MAX = 84;  // C6

// Maps knob 0–1023 to MIDI note in C3(48)–C6(84) range using the same
// pitchBend curve as the D3 harmonic engine (BEND_START breakpoint at 0.25).
static inline uint8_t d3ChromaKnobToNote(int knobValue) {
  float norm = knobValue / 1023.0f;
  const float BEND_START = 0.25f;
  float pitchBend;
  if (norm <= BEND_START) {
    pitchBend = 0.60f * (norm / BEND_START);
  } else {
    float blend = (norm - BEND_START) / (1.0f - BEND_START);
    pitchBend = 0.60f + 0.40f * (blend * blend);
  }
  float semi = pitchBend * (float)(D3_HARM_NOTE_MAX - D3_HARM_NOTE_MIN);
  return (uint8_t)constrain((int)(semi + 0.5f) + D3_HARM_NOTE_MIN,
                             D3_HARM_NOTE_MIN, D3_HARM_NOTE_MAX);
}

// Sets all D3 oscillators (606 bank, FM, perc) to harmonic ratios for a given
// MIDI note.  Called per-step during playback when D3 chroma mode is active.
// Filter tracking is handled separately by the knob handler — not per-step.
void applyD3ChromaFreq(uint8_t midiNote) {
  float baseHz = midiToFreq(midiNote);
  AudioNoInterrupts();
  // 606 bank: power chord spacing
  d3606Osc1.frequency(baseHz * 1.0f);   // root
  d3606Osc2.frequency(baseHz * 1.5f);   // fifth
  d3606Osc3.frequency(baseHz * 2.0f);   // octave
  d3606Osc4.frequency(baseHz * 3.0f);   // fifth + octave
  d3606Osc5.frequency(baseHz * 4.0f);   // two octaves
  d3606Osc6.frequency(baseHz * 6.0f);   // fifth + two octaves
  // FM voice: octave-spaced carrier-modulator pairs (2:1 ratios)
  d3FmCarrier1.frequency(baseHz * 2.0f);
  d3FmMod1.frequency(baseHz * 4.0f);
  d3FmMod1.amplitude(0.35f);
  d3FmCarrier2.frequency(baseHz * 3.0f);
  d3FmMod2.frequency(baseHz * 6.0f);
  d3FmMod2.amplitude(0.30f);
  // Perc: same base pitch
  d3Perc.frequency(baseHz);
  AudioInterrupts();
}

// D2 Decay curve: 75–93ms (0–50%), 93–225ms (51–75%), 225–500ms (75–100%)
static inline float d2DecayCurve(int knobValue) {
  float norm = normalizeKnob(knobValue);
  if (norm <= 0.5f) {
    float t = norm / 0.5f;             // 0..1 over bottom half
    return 75.0f + t * 18.0f;          // 75 -> 93ms
  } else if (norm <= 0.75f) {
    float t = (norm - 0.5f) / 0.25f;   // 0..1 over 50–75%
    return 93.0f + t * 132.0f;         // 93 -> 225ms
  } else {
    float t = (norm - 0.75f) / 0.25f;  // 0..1 over 75–100%
    return 225.0f + t * 275.0f;        // 225 -> 500ms
  }
}

// D3 Filter curve: 800–7500 Hz exponential (log-spaced for natural feel)
static inline float d3FilterCurve(int knobValue) {
  float norm = normalizeKnob(knobValue);
  return 1200.0f * expf(norm * 2.303f);  // ln(12000/1200) ≈ 2.303
}

// BPM curve: 60–400 (first 85%) then 900–999 (remaining 15%, hyperspeed), rounded to 0.5
// NOTE: The 400–900 gap is intentional — hyperspeed is a separate creative effect.
static inline float bpmFromKnob(int knobValue) {
  float norm = normalizeKnob(knobValue);
  float bpmValue;
  if (norm <= 0.85f) {
    // 0–85%: 60 → 400 BPM (normal range)
    float blend = norm / 0.85f;
    bpmValue = 60.0f + blend * (400.0f - 60.0f);
  } else {
    // 85–100%: 900 → 999 BPM (hyperspeed)
    float blend = (norm - 0.85f) / 0.15f;
    bpmValue = 900.0f + blend * (999.0f - 900.0f);
  }
  return floorf(bpmValue * 2.0f + 0.5f) * 0.5f;
}

// Accent mode from knob position — maps knob to one of 15 accent modes (OFF + 14 patterns).
// AccentMode enum values are sequential (0=OFF, 1=PICKUP ... 14=CASCADE).
static inline uint8_t accentModeFromKnob(int knobValue) {
  const int ACCENT_DEADBAND = 24;
  if (knobValue <= ACCENT_DEADBAND) return ACCENT_OFF;
  int zone = map(knobValue, ACCENT_DEADBAND + 1, 1023, 1, 14);
  return (uint8_t)constrain(zone, 1, (int)ACCENT_CASCADE);
}

// Delay ratio index from knob — finds the closest beat-synced ratio within delay limit
static inline int delayRatioFromKnob(int knobValue, float currentBpm) {
  float msPerBeat = 60000.0f / currentBpm;
  float maxRatio = 1400.0f / msPerBeat;

  int maxIdx = 0;
  for (int ratioIndex = 0; ratioIndex < NUM_RATIOS; ratioIndex++) {
    if (quantizeRatios[ratioIndex] <= maxRatio) {
      maxIdx = ratioIndex;
    } else {
      break;
    }
  }

  int ratioIdx = (int)(normalizeKnob(knobValue) * maxIdx + 0.5f);
  return constrain(ratioIdx, 0, maxIdx);
}

// Knob handler dispatch table — 32 display + 32 engine functions.
// Replaces the former 32-case switch blocks in updateParameterDisplay()
// and applyKnobToEngine(). See knob_handlers.h for per-knob functions.
#include "knob_handlers.h"

void updateParameterDisplay(uint8_t idx, int knobValue) {
  // sysTickMs is a single aligned 32-bit read (atomic LDR on ARM Cortex-M7).
  // parameterOverlayStartTick is main-loop only — no guard needed.
  parameterOverlayStartTick = sysTickMs;
  activeRail = RAIL_NONE;
  if (idx < 32) knobTable[idx].display(idx, knobValue);
}

void applyKnobToEngine(uint8_t idx, int knobValue) {
  if (idx < 32) knobTable[idx].engine(idx, knobValue);
}


// ============================================================================
//  Initialization from Hardware
// ============================================================================

void initKnobsFromHardware() {
  // Read all knobs, settle filters, apply to engine, and store boot values.
  // Boot-lock prevents ADC drift from changing params until the user moves a knob.
  for (int idx = 0; idx < knobCount; idx++) {
    int rawValue = readKnobRaw(idx);

    // Update filter multiple times to settle it
    for (int i = 0; i < 4; i++) {
      analog[idx]->update(rawValue);
    }

    knobBootValue[idx] = rawValue;
    knobUnlocked[idx] = false;

    applyKnobToEngine(idx, rawValue);
  }

  // Re-sync delay time: knob 24 (delay) was processed before knob 27 (BPM),
  // so it computed against the default 120 BPM. Now that BPM is finalized,
  // recalculate the delay to match the actual physical BPM knob position.
  applyKnobToEngine(24, analog[24]->getValue());
}

// OPTIMIZATION: round-robin knob scanning — reads 8 knobs per loop iteration
// instead of all 32, reducing per-loop delayMicroseconds overhead by 4x
void updateKnobs() {
  static uint8_t knobScanGroup = 0;
  int start = knobScanGroup * 8;
  int end = start + 8;

  for (int idx = start; idx < end; idx++) {
    int rawValue = readKnobRaw(idx);
    analog[idx]->update(rawValue);

    if (analog[idx]->hasChanged()) {
      int knobValue = analog[idx]->getValue();

      // Boot-lock: ignore small ADC drift until the user intentionally moves
      // the knob past the unlock threshold from its power-on position.
      if (!knobUnlocked[idx]) {
        int diff = knobValue - knobBootValue[idx];
        if (diff < 0) diff = -diff;
        if (diff < KNOB_UNLOCK_THRESHOLD) continue;
        knobUnlocked[idx] = true;
      }

      updateParameterDisplay(idx, knobValue);
      applyKnobToEngine(idx, knobValue);
    }
  }

  knobScanGroup = (knobScanGroup + 1) & 3;  // 0,1,2,3 → cycle through 4 groups
}

// ============================================================================
//  UI Helpers
// ============================================================================

// Draw white text with a 2-pixel black outline for readability over the scope waveform.
// Stamps black text at 8 offsets (4 cardinal + 4 diagonal, 2px each) then white on top.
void drawOutlinedText(int x, int y, const char* text) {
  static const int8_t offsets[][2] = {
    {-2, 0}, {2, 0}, {0, -2}, {0, 2},   // cardinal 2px
    {-2,-2}, {2,-2}, {-2, 2}, {2, 2}     // diagonal 2px
  };
  display.setTextColor(0);
  for (auto& o : offsets) {
    display.setCursor(x + o[0], y + o[1]);
    display.print(text);
  }
  display.setTextColor(1);
  display.setCursor(x, y);
  display.print(text);
}

static inline void drawCaretRail(int x, int y, int w, int h, int caretX) {
  display.drawRect(x, y, w, h, 1);
  int cx = constrain(caretX, x + 1, x + w - 2);
  display.drawLine(cx, y - 2, cx, y + h + 2, 1);
}

static inline void labelAtCenter(const char* text, int centerX, int y) {
  int16_t x1, y1;
  uint16_t w, h;
  display.getTextBounds(text, 0, 0, &x1, &y1, &w, &h);
  int x = centerX - (w / 2);
  drawOutlinedText(x, y, text);
}

void renderVoiceRails() {
  // Rail displayed alongside scope: label text at y=23, rail bar at y=44
  const int railX = 6;
  const int railY = 44;
  const int railW = 116;
  const int railH = 10;
  const int labelY = 23;

  display.setTextSize(1);

  // Black rectangle behind labels + rail so they're visible over the scope waveform
  display.fillRect(railX - 2, labelY - 2, railW + 4, (railY + railH) - labelY + 5, 0);

  if (activeRail == RAIL_D1_SHAPE) {
    drawCaretRail(railX, railY, railW, railH, railX + (int)(uiMixD1Shape * railW));
    int third = railW / 3;
    labelAtCenter("SIN", railX + third * 0 + third / 2, labelY);
    labelAtCenter("SAW", railX + third * 1 + third / 2, labelY);
    labelAtCenter("SQR", railX + third * 2 + third / 2, labelY);
    // Zone thresholds match engine crossfade (case 1):
    // sine+saw blend for first half, saw+square blend for second half
    int zone = (uiMixD1Shape < 0.25f) ? 0    // SIN dominant
             : (uiMixD1Shape < 0.75f) ? 1    // SAW dominant (peaks at 50%)
                                      : 2;   // SQR dominant
    int zx = railX + zone * third + 1;
    int zw = third - 2;
    display.fillRect(zx, railY + 1, zw, railH - 2, 1);

  } else if (activeRail == RAIL_D2_VOICE) {
    int caret = railX + (int)(uiMixD2Voice * railW);
    drawCaretRail(railX, railY, railW, railH, caret);
    labelAtCenter("CLAP", railX + 14, labelY);
    labelAtCenter("SNARE", railX + railW - 14, labelY);
    int fillW = max(1, caret - railX);
    if (fillW > 2) display.fillRect(railX + 1, railY + 1, fillW - 2, railH - 2, 1);

  } else if (activeRail == RAIL_D3_VOICE) {
    drawCaretRail(railX, railY, railW, railH, railX + (int)(uiMixD3Voice * railW));
    int third = railW / 3;
    labelAtCenter("606", railX + third * 0 + third / 2, labelY);
    labelAtCenter("FM", railX + third * 1 + third / 2, labelY);
    labelAtCenter("PERC", railX + third * 2 + third / 2, labelY);
    // Zone thresholds match engine crossfade midpoints (case 18):
    // 606 solo < 6%, crossfade 6–46%, FM solo 46–65%, crossfade 65–94%, PERC solo > 94%
    int zone = (uiMixD3Voice < 0.27f)  ? 0    // 606 side (solo + crossfade into FM)
             : (uiMixD3Voice < 0.80f)  ? 1    // FM zone (crossfade + solo + crossfade)
                                       : 2;   // PERC side (crossfade from FM + solo)
    int zx = railX + zone * third + 1;
    int zw = third - 2;
    display.fillRect(zx, railY + 1, zw, railH - 2, 1);
  }
}

// SPI push guard — returns true when it's safe to start a blocking OLED
// transfer (~15-25ms). Returns false if audio timing work is pending or
// imminent. Musical timing always wins over display updates.
// Called from updateDisplay() for both the PPQN mode and normal display paths.
bool isSafeToPushOled(uint32_t nowMs) {
  // Steps waiting: consume them first, never block with pending audio work
  if (pendingStepCount > 0) return false;

  // Drop-in display block (suppress push for 500ms after PLAY press)
  if (displayBlockedUntilTick > 0) {
    if ((int32_t)(displayBlockedUntilTick - nowMs) > 0) {
      return false;
    } else {
      displayBlockedUntilTick = 0;  // main-loop only — no interrupt guard required
    }
  }

  // Protect steps B and A — read all ISR-shared timing variables atomically
  if (transportState == RUN_EXT) {
    uint32_t subdivDue;
    uint32_t ema;
    uint32_t lastP;
    noInterrupts();
    subdivDue = subdivTimerDueUs;
    ema = extIntervalEMA;
    lastP = lastPulseMicros;
    interrupts();

    // Step B: subdivision timer due within 25ms
    // micros() called outside noInterrupts() — benign TOCTOU: a slightly later
    // timestamp only makes remaining smaller, so we err toward skipping the push.
    if (subdivDue > 0) {
      int32_t remaining = (int32_t)(subdivDue - micros());
      if (remaining > 0 && remaining < 25000) return false;
    }

    // Step A: next pulse predicted within 25ms from EMA
    if (ema > 0 && lastP > 0) {
      int32_t remaining = (int32_t)((lastP + ema) - micros());
      if (remaining > 0 && remaining < 25000) return false;
    }
  }

  return true;
}

// ============================================================================
//  OLED Drawing — sub-renderers
// ============================================================================

// Top bar: BPM/EXT, track digit, choke, MEM slot, transport icon.
void renderTopBar(float bpmSnap, uint8_t trackSnap, int chokeSnap,
                  uint8_t slotSnap, bool playingSnap) {
  // MONOBASS mode: replace entire toolbar with centered "MONOBASS" text
  if (monoBass.active) {
    display.setTextSize(2);
    int16_t x1, y1;
    uint16_t w, h;
    display.getTextBounds("MONOBASS", 0, 0, &x1, &y1, &w, &h);
    display.setCursor((128 - w) / 2, 2);
    display.print("MONOBASS");
    display.setTextSize(1);
    return;
  }

  // BPM / EXT clock state
  display.setCursor(0, 0);
  if (extBpmDisplay > 0.0f) {
    display.print("EXT");
    display.setCursor(0, 10);
    float snapped = floorf(extBpmDisplay * 2.0f + 0.5f) * 0.5f;
    display.print(snapped, 1);
  } else {
    display.print("BPM");
    display.setCursor(0, 10);
    display.print(bpmSnap, 1);
  }

  // Size-2 track digit
  display.setTextSize(2);
  display.setCursor(38, 2);
  display.print(trackSnap + 1);
  display.setTextSize(1);

  // Choke
  display.setCursor(58, 0);
  display.print("CHOKE");
  {
    char chokeBuf[6];
    if (chokeSnap == 0) {
      strcpy(chokeBuf, "OFF");
    } else {
      snprintf(chokeBuf, sizeof(chokeBuf), "%+d%%", chokeSnap);
    }
    display.setCursor(73 - (int)strlen(chokeBuf) * 3, 10);
    display.print(chokeBuf);
  }

  // Memory slot
  display.setCursor(95, 0);
  display.print("MEM");
  {
    char memBuf[4];
    snprintf(memBuf, sizeof(memBuf), "%d", slotSnap + 1);
    display.setCursor(104 - (int)strlen(memBuf) * 3, 10);
    display.print(memBuf);
  }

  // Transport icon
  if (playingSnap) {
    display.drawBitmap(118, 4, image_play_bits, 10, 10, 1);
  } else {
    display.drawBitmap(118, 4, image_stop_bits, 10, 10, 1);
  }
}

// renderMonoBassScope() is now in monobass.h

// Chroma note select: large note name when a chroma step is held.
// Returns true if it drew content (suppresses oscilloscope).
bool renderChromaNoteSelect() {
  bool noteSelectActive = (d1ChromaHeldStep >= 0) || (d2ChromaHeldStep >= 0) || (d3ChromaHeldStep >= 0);
  if (!noteSelectActive) return false;

  int stepNum;
  uint8_t midiNote;
  if (d1ChromaHeldStep >= 0) {
    stepNum = d1ChromaHeldStep;
    midiNote = d1ChromaNote[d1ChromaHeldStep];
  } else if (d2ChromaHeldStep >= 0) {
    stepNum = d2ChromaHeldStep;
    midiNote = d2ChromaNote[d2ChromaHeldStep];
  } else {
    stepNum = d3ChromaHeldStep;
    midiNote = d3ChromaNote[d3ChromaHeldStep];
  }

  char noteName[8];
  formatChromaNote(midiNote, noteName);

  // "STEP X" label — centered at top of scope area
  display.setTextSize(1);
  char stepLabel[10];
  snprintf(stepLabel, sizeof(stepLabel), "STEP %d", stepNum + 1);
  int16_t sx1, sy1;
  uint16_t sw, sh;
  display.getTextBounds(stepLabel, 0, 0, &sx1, &sy1, &sw, &sh);
  display.setCursor((128 - sw) / 2, 24);
  display.print(stepLabel);

  // Large note name
  display.setTextSize(3);
  int16_t nx1, ny1;
  uint16_t nw, nh;
  display.getTextBounds(noteName, 0, 0, &nx1, &ny1, &nw, &nh);
  display.setCursor((128 - nw) / 2, 35);
  display.print(noteName);
  display.setTextSize(1);
  return true;
}

// Chroma dot indicator — bottom bar dots for active chroma channels.
void renderChromaDots() {
  // All dots suppressed during MONOBASS — WF chroma is always on there and the
  // idle grid / scope uses the full display area without room for the dot bar.
  if (monoBass.active) return;
  bool showD1 = d1ChromaMode;
  bool showD2 = d2ChromaMode;
  bool showD3 = d3ChromaMode;
  bool showWF = wfChromaMode;
  if (!showD1 && !showD2 && !showD3 && !showWF) return;

  const bool chromaActive[4] = {
    showD1, showD2, showD3, showWF
  };
  const int dotCenters[4] = { 16, 48, 80, 112 };
  const int dotSize = 4;
  const int padSize = dotSize + 2;  // 1px black border around each dot
  const int dotY = 59;
  const int padY = dotY - 1;

  for (int i = 0; i < 4; i++) {
    if (chromaActive[i]) {
      // Clear only behind this dot (not a full-width strip)
      int px = dotCenters[i] - padSize / 2;
      display.fillRect(px, padY, padSize, padSize, SH110X_BLACK);
      int dx = dotCenters[i] - dotSize / 2;
      display.fillRect(dx, dotY, dotSize, dotSize, SH110X_WHITE);
    }
  }
}

// Parameter overlay — bottom text or voice rails.
void renderParameterOverlay(uint8_t railSnap, const char* param1Snap,
                            const char* param2Snap) {
  if (railSnap == RAIL_NONE) {
    display.setTextSize(1);
    const int bottomY = 56;
    if (param1Snap[0]) {
      drawOutlinedText(5, bottomY, param1Snap);
    }
    if (param2Snap[0]) {
      int16_t x1, y1;
      uint16_t w2, h2;
      display.getTextBounds(param2Snap, 0, 0, &x1, &y1, &w2, &h2);
      drawOutlinedText(128 - w2 - 2, bottomY, param2Snap);
    }
  } else {
    renderVoiceRails();
  }
}

// ============================================================================
//  OLED Drawing — main dispatcher
// ============================================================================

void updateDisplay() {
  // Snapshot time first
  uint32_t nowMs;
  noInterrupts();
  nowMs = sysTickMs;
  interrupts();

  // Count-in display — shows "4" "3" "2" "1" countdown while armed
  if (armed && transportState == RUN_EXT) {
    display.clearDisplay();
    display.setFont(NULL);
    display.setTextColor(1);
    display.setTextWrap(false);

    // Calculate beat countdown: 4, 3, 2, 1
    // pulsesPerCycle = numSteps * ppqn / STEPS_PER_BEAT
    // pulsesPerBeat = ppqn
    // pulsesCounted = pulsesPerCycle - armPulseCountdown
    // Snapshot both ISR-written volatiles atomically before arithmetic.
    // armPulseCountdown is ARM-atomic (uint16_t LDRH), but an ISR decrement
    // between a separate ppqn read and the countdown comparison would make
    // pulsesPerCycle - armPulseCountdown inconsistent (off by one beat).
    uint8_t p;
    uint16_t armSnap;
    noInterrupts();
    p       = ppqn;
    armSnap = armPulseCountdown;
    interrupts();
    uint16_t pulsesPerCycle = (uint16_t)numSteps * p / STEPS_PER_BEAT;
    uint8_t beatsPerCycle = numSteps / STEPS_PER_BEAT;  // 4

    uint8_t currentBeat = 0;
    if (armSnap < pulsesPerCycle) {
      uint16_t pulsesCounted = pulsesPerCycle - armSnap;
      currentBeat = (pulsesCounted - 1) / p + 1;  // 1-based beat number
    }
    // Countdown: show beatsRemaining = beatsPerCycle - currentBeat + 1
    // But before first pulse (currentBeat=0), show beatsPerCycle
    uint8_t countdown = (currentBeat == 0)
                        ? beatsPerCycle
                        : beatsPerCycle - currentBeat + 1;

    // Large centered countdown number
    display.setTextSize(4);  // ~24px wide per char
    display.setCursor(52, 16);
    display.print(countdown);

    // SPI push — no timing guard needed during count-in (no steps firing)
    display.display();
    noInterrupts();
    lastFrameDrawTick = nowMs;
    interrupts();
    return;
  }

  // PPQN selection mode — full-screen takeover, skip normal UI
  if (ppqnModeActive) {
    display.clearDisplay();
    display.setFont(NULL);
    display.setTextColor(1);
    display.setTextWrap(false);

    display.setTextSize(2);
    display.setCursor(0, 0);
    display.print("PPQN SELECT");

    display.setTextSize(1);
    display.setCursor(28, 20);
    display.print("TAP TO CYCLE");
    display.setCursor(28, 32);
    display.print("HOLD TO SAVE");

    display.setTextSize(2);
    {
      char ppqnBuf[4];
      snprintf(ppqnBuf, sizeof(ppqnBuf), "%d", ppqnModeSelection);
      display.setCursor(65 - (int)strlen(ppqnBuf) * 6, 48);
      display.print(ppqnBuf);
    }

    if (isSafeToPushOled(nowMs)) {
      display.display();
      noInterrupts();
      lastFrameDrawTick = nowMs;
      interrupts();
    }
    return;
  }

  // Snapshot all state we will render so a single frame is coherent
  float bpmSnap;
  uint8_t trackSnap;
  int chokeSnap;
  uint8_t slotSnap;
  bool playingSnap;
  uint32_t overlayStartSnap;
  uint8_t railSnap;
  char param1Snap[24];
  char param2Snap[24];

  // Snapshot ISR-shared state with interrupts disabled
  noInterrupts();
  playingSnap = sequencePlaying;
  interrupts();

  // Main-loop only — no ISR access, safe without guards
  bpmSnap = bpm;
  trackSnap = activeTrack;
  chokeSnap = chokeDisplayPercent;
  slotSnap = activeSaveSlot;
  overlayStartSnap = parameterOverlayStartTick;
  railSnap = activeRail;

  snprintf(param1Snap, sizeof(param1Snap), "%s", displayParameter1);
  snprintf(param2Snap, sizeof(param2Snap), "%s", displayParameter2);

  // Overlay state
  bool overlayActiveNow =
    ((uint32_t)(nowMs - overlayStartSnap) < PARAMETER_OVERLAY_DURATION_MS);

  display.clearDisplay();

  // Setup text defaults
  display.setFont(NULL);
  display.setTextColor(1);
  display.setTextSize(1);
  display.setTextWrap(false);

  // Double-thick horizontal divider (y=19..20) and left vertical border (x=0..1)
  display.drawLine(1, 21, 1, 63, 1);
  display.drawLine(1, 20, 127, 20, 1);
  display.drawLine(0, 63, 0, 20, 1);
  display.drawLine(1, 19, 127, 19, 1);

  renderTopBar(bpmSnap, trackSnap, chokeSnap, slotSnap, playingSnap);

  // Scope area: chroma note select > oscilloscope, then MONOBASS overlay on top
  bool noteSelectActive = renderChromaNoteSelect();
  if (!noteSelectActive) {
    drawScopeWaveform(2, 22, SCOPE_DISPLAY_HEIGHT);
  }
  renderMonoBassScope(nowMs);  // outlined overlay on top of scope

  // Suppress small parameter overlay when scope area owns the display.
  // In MONOBASS, allow D1 voice rail through (D1 shape knob is still active).
  if (noteSelectActive) overlayActiveNow = false;
  if (monoBass.active && railSnap != RAIL_D1_SHAPE) overlayActiveNow = false;
  if (overlayActiveNow) {
    renderParameterOverlay(railSnap, param1Snap, param2Snap);
  } else {
    // Chroma dots share the bottom strip with the parameter overlay —
    // only draw them when the overlay is not visible.
    renderChromaDots();
  }

  // Fire any steps queued during framebuffer drawing, before the
  // blocking SPI transfer adds another 15-25ms of latency.
  if (playingSnap) {
    playSequence();
  }

  if (isSafeToPushOled(nowMs)) {
    display.display();

    // Update OLED watchdog timestamp only after a successful push.
    // On skipped pushes, the stale timestamp causes an immediate retry
    // next loop iteration — by then step B has fired and the push succeeds.
    noInterrupts();
    lastFrameDrawTick = nowMs;
    interrupts();
  }
}